/**
 * AIC (Artificial Intelligence Command) Report System
 * Strategic intelligence and status reports generated by the AIC
 * @tag #aic #report #intelligence #strategy
 */

// ============================================================================
// TYPES
// ============================================================================

export type AICReportCategory =
  | 'intel'
  | 'threat'
  | 'strategic'
  | 'economic'
  | 'military'
  | 'diplomatic'
  | 'research'
  | 'expansion'
  | 'internal';

export type AICReportSeverity =
  | 'informational'
  | 'advisory'
  | 'warning'
  | 'critical'
  | 'urgent';

export type AICReportStatus =
  | 'pending'
  | 'reviewed'
  | 'actioned'
  | 'archived'
  | 'escalated';

export type AICReportTrigger =
  | 'scheduled'
  | 'event_detected'
  | 'threshold_exceeded'
  | 'player_requested'
  | 'system_alert'
  | 'intel_update';

export interface AICReportSource {
  entityId: string;
  entityName: string;
  entityType: 'sensor_network' | 'spy_network' | 'fleet_intel' | 'economic_analysis' | 'diplomatic_corps' | 'research_division' | 'internal_affairs' | 'strategic_command';
  reliability: number; // 0-1
}

export interface AICReportData {
  id: string;
  category: AICReportCategory;
  severity: AICReportSeverity;
  status: AICReportStatus;
  trigger: AICReportTrigger;
  timestamp: number;
  title: string;
  summary: string;
  details: string;
  source: AICReportSource;
  relatedEntityId?: string;
  relatedEntityType?: string;
  confidence: number; // 0-1
  recommendations: readonly string[];
  actionable: boolean;
  expiryTimestamp?: number;
}

// ============================================================================
// REPORT CATEGORY CONFIGURATION
// ============================================================================

export interface AICReportCategoryConfig {
  category: AICReportCategory;
  name: string;
  description: string;
  icon: string;
  color: string;
  priority: number;
  defaultConfidence: number;
  updateFrequency: number; // minutes
  maxActiveReports: number;
  defaultRetentionDays: number;
}

export const AIC_REPORT_CATEGORIES: readonly AICReportCategoryConfig[] = [
  {
    category: 'intel',
    name: 'Intelligence',
    description: 'Gathered intelligence on enemy movements, fleet positions, and unknown activity',
    icon: '🕵️',
    color: '#6366f1',
    priority: 8,
    defaultConfidence: 0.6,
    updateFrequency: 30,
    maxActiveReports: 25,
    defaultRetentionDays: 7,
  },
  {
    category: 'threat',
    name: 'Threat Assessment',
    description: 'Immediate and emerging threats to empire security and territory',
    icon: '⚠️',
    color: '#ef4444',
    priority: 10,
    defaultConfidence: 0.7,
    updateFrequency: 15,
    maxActiveReports: 15,
    defaultRetentionDays: 14,
  },
  {
    category: 'strategic',
    name: 'Strategic Overview',
    description: 'Long-term strategic analysis and empire-wide status assessment',
    icon: '🎯',
    color: '#8b5cf6',
    priority: 7,
    defaultConfidence: 0.8,
    updateFrequency: 60,
    maxActiveReports: 10,
    defaultRetentionDays: 30,
  },
  {
    category: 'economic',
    name: 'Economic Analysis',
    description: 'Resource production, trade routes, and market analysis',
    icon: '💰',
    color: '#22c55e',
    priority: 6,
    defaultConfidence: 0.85,
    updateFrequency: 45,
    maxActiveReports: 20,
    defaultRetentionDays: 14,
  },
  {
    category: 'military',
    name: 'Military Assessment',
    description: 'Fleet readiness, defensive capability, and combat effectiveness',
    icon: '⚔️',
    color: '#dc2626',
    priority: 9,
    defaultConfidence: 0.75,
    updateFrequency: 20,
    maxActiveReports: 20,
    defaultRetentionDays: 7,
  },
  {
    category: 'diplomatic',
    name: 'Diplomatic Briefing',
    description: 'Foreign relations, alliance status, and diplomatic incidents',
    icon: '🤝',
    color: '#3b82f6',
    priority: 5,
    defaultConfidence: 0.65,
    updateFrequency: 60,
    maxActiveReports: 15,
    defaultRetentionDays: 14,
  },
  {
    category: 'research',
    name: 'Research Progress',
    description: 'Technology advancement, discovery milestones, and research efficiency',
    icon: '🔬',
    color: '#06b6d4',
    priority: 4,
    defaultConfidence: 0.9,
    updateFrequency: 120,
    maxActiveReports: 10,
    defaultRetentionDays: 30,
  },
  {
    category: 'expansion',
    name: 'Expansion Report',
    description: 'Colony development, territorial growth, and colonization opportunities',
    icon: '🚀',
    color: '#f59e0b',
    priority: 5,
    defaultConfidence: 0.8,
    updateFrequency: 60,
    maxActiveReports: 15,
    defaultRetentionDays: 14,
  },
  {
    category: 'internal',
    name: 'Internal Affairs',
    description: 'Empire stability, faction relations, and internal security',
    icon: '🏛️',
    color: '#ec4899',
    priority: 6,
    defaultConfidence: 0.7,
    updateFrequency: 45,
    maxActiveReports: 12,
    defaultRetentionDays: 21,
  },
];

// ============================================================================
// REPORT SEVERITY CONFIGURATION
// ============================================================================

export interface AICReportSeverityConfig {
  severity: AICReportSeverity;
  name: string;
  description: string;
  color: string;
  icon: string;
  responseDeadlineMinutes: number;
  requiresAcknowledgment: boolean;
  autoEscalateAfterMinutes: number;
}

export const AIC_REPORT_SEVERITIES: readonly AICReportSeverityConfig[] = [
  {
    severity: 'informational',
    name: 'Informational',
    description: 'Routine updates and general awareness items',
    color: '#6b7280',
    icon: 'ℹ️',
    responseDeadlineMinutes: 0,
    requiresAcknowledgment: false,
    autoEscalateAfterMinutes: 0,
  },
  {
    severity: 'advisory',
    name: 'Advisory',
    description: 'Recommended attention but not immediately critical',
    color: '#3b82f6',
    icon: '📋',
    responseDeadlineMinutes: 240,
    requiresAcknowledgment: false,
    autoEscalateAfterMinutes: 0,
  },
  {
    severity: 'warning',
    name: 'Warning',
    description: 'Potential issues requiring timely attention',
    color: '#f59e0b',
    icon: '⚡',
    responseDeadlineMinutes: 60,
    requiresAcknowledgment: true,
    autoEscalateAfterMinutes: 180,
  },
  {
    severity: 'critical',
    name: 'Critical',
    description: 'Immediate action recommended to prevent significant losses',
    color: '#ef4444',
    icon: '🚨',
    responseDeadlineMinutes: 15,
    requiresAcknowledgment: true,
    autoEscalateAfterMinutes: 45,
  },
  {
    severity: 'urgent',
    name: 'Urgent',
    description: 'Requires immediate action. Empire assets at immediate risk',
    color: '#dc2626',
    icon: '🔴',
    responseDeadlineMinutes: 5,
    requiresAcknowledgment: true,
    autoEscalateAfterMinutes: 15,
  },
];

// ============================================================================
// REPORT TEMPLATES
// ============================================================================

export interface AICReportTemplate {
  id: string;
  category: AICReportCategory;
  severity: AICReportSeverity;
  title: string;
  summaryTemplate: string;
  detailsTemplate: string;
  triggerType: AICReportTrigger;
  thresholdValues?: Record<string, number>;
  sourceEntityType: AICReportSource['entityType'];
  baseConfidence: number;
  actionable: boolean;
  cooldownMinutes: number;
}

export const AIC_REPORT_TEMPLATES: readonly AICReportTemplate[] = [
  {
    id: 'intel-fleet-movement',
    category: 'intel',
    severity: 'warning',
    title: 'Enemy Fleet Movement Detected',
    summaryTemplate: '{enemyName} fleet detected moving toward {sector}',
    detailsTemplate: 'Sensor arrays have detected a {fleetSize}-ship {enemyType} fleet moving from {origin} toward {destination}. Estimated arrival in {eta} hours. Fleet composition includes {composition}.',
    triggerType: 'event_detected',
    sourceEntityType: 'sensor_network',
    baseConfidence: 0.7,
    actionable: true,
    cooldownMinutes: 30,
  },
  {
    id: 'intel-spy-report',
    category: 'intel',
    severity: 'advisory',
    title: 'Spy Network Report',
    summaryTemplate: 'Intel gathered on {targetName}',
    detailsTemplate: 'Operatives have reported on {targetName}\'s current activities: {activities}. Estimated military strength: {militaryStrength}. Resource stockpiles: {resources}. Diplomatic stance: {stance}.',
    triggerType: 'intel_update',
    sourceEntityType: 'spy_network',
    baseConfidence: 0.55,
    actionable: false,
    cooldownMinutes: 120,
  },
  {
    id: 'threat-imminent-attack',
    category: 'threat',
    severity: 'critical',
    title: 'Imminent Attack Warning',
    summaryTemplate: '{enemyName} forces preparing to attack {targetLocation}',
    detailsTemplate: 'High-confidence intel indicates {enemyName} will launch an attack on {targetLocation} within {eta} hours. Estimated force: {fleetPower}. Recommend immediate defensive positioning.',
    triggerType: 'event_detected',
    sourceEntityType: 'fleet_intel',
    baseConfidence: 0.75,
    actionable: true,
    cooldownMinutes: 15,
  },
  {
    id: 'threat-territorial-incursion',
    category: 'threat',
    severity: 'warning',
    title: 'Territorial Incursion Detected',
    summaryTemplate: '{entityName} has entered claimed space in {sector}',
    detailsTemplate: '{entityName} vessels have been detected within sovereign territory in the {sector} sector. Current position: {coordinates}. No hostile action detected yet, but standard protocols recommend verification.',
    triggerType: 'event_detected',
    sourceEntityType: 'sensor_network',
    baseConfidence: 0.8,
    actionable: true,
    cooldownMinutes: 20,
  },
  {
    id: 'strategic-empire-assessment',
    category: 'strategic',
    severity: 'informational',
    title: 'Empire Strategic Assessment',
    summaryTemplate: 'Strategic overview of empire status',
    detailsTemplate: 'Empire Level: {empireLevel} | Authority Tier: {authorityTier} | Controlled Systems: {controlledSystems} | Total Fleet Power: {fleetPower} | Research Level: {researchLevel} | Economic Output: {economicOutput}. Overall assessment: {assessment}.',
    triggerType: 'scheduled',
    sourceEntityType: 'strategic_command',
    baseConfidence: 0.9,
    actionable: false,
    cooldownMinutes: 60,
  },
  {
    id: 'economic-resource-shortfall',
    category: 'economic',
    severity: 'warning',
    title: 'Resource Shortfall Warning',
    summaryTemplate: '{resourceType} production deficit detected',
    detailsTemplate: 'Current {resourceType} production ({production}/hr) is insufficient to meet demand ({demand}/hr). Reserves will be depleted in {estimatedHours} hours at current consumption rates. Suggested actions: {suggestions}.',
    triggerType: 'threshold_exceeded',
    sourceEntityType: 'economic_analysis',
    baseConfidence: 0.9,
    actionable: true,
    cooldownMinutes: 60,
  },
  {
    id: 'economic-trade-route-disruption',
    category: 'economic',
    severity: 'advisory',
    title: 'Trade Route Disruption',
    summaryTemplate: 'Trade route {routeName} disrupted',
    detailsTemplate: 'Trade route {routeName} between {origin} and {destination} has been disrupted due to {reason}. Estimated economic impact: {impact} credits per hour. Alternative routes available: {alternatives}.',
    triggerType: 'event_detected',
    sourceEntityType: 'economic_analysis',
    baseConfidence: 0.85,
    actionable: true,
    cooldownMinutes: 30,
  },
  {
    id: 'military-fleet-readiness',
    category: 'military',
    severity: 'advisory',
    title: 'Fleet Readiness Report',
    summaryTemplate: 'Fleet {fleetName} readiness assessment',
    detailsTemplate: 'Fleet {fleetName} (based at {location}) at {readinessPercent}% readiness. Ships operational: {operational}/{total}. Average hull integrity: {hullIntegrity}%. Supply status: {supplyStatus}. Crew morale: {morale}.',
    triggerType: 'scheduled',
    sourceEntityType: 'fleet_intel',
    baseConfidence: 0.85,
    actionable: false,
    cooldownMinutes: 30,
  },
  {
    id: 'military-defensive-gap',
    category: 'military',
    severity: 'warning',
    title: 'Defensive Gap Identified',
    summaryTemplate: 'Defensive weakness detected in {sector}',
    detailsTemplate: 'Analysis reveals inadequate defensive coverage in the {sector} sector. Current defensive rating: {defenseRating} (below recommended {recommendedRating}). Enemy presence in region: {enemyPresence}. Recommend deploying {recommendedForces}.',
    triggerType: 'system_alert',
    sourceEntityType: 'strategic_command',
    baseConfidence: 0.8,
    actionable: true,
    cooldownMinutes: 120,
  },
  {
    id: 'diplomatic-relation-shift',
    category: 'diplomatic',
    severity: 'advisory',
    title: 'Diplomatic Relation Change',
    summaryTemplate: '{factionName} stance shifted to {newStance}',
    detailsTemplate: '{factionName} has shifted their diplomatic stance from {previousStance} to {newStance}. Triggering event: {triggerEvent}. This may affect {affectedAreas}. Recommended diplomatic response: {recommendation}.',
    triggerType: 'event_detected',
    sourceEntityType: 'diplomatic_corps',
    baseConfidence: 0.7,
    actionable: true,
    cooldownMinutes: 60,
  },
  {
    id: 'research-breakthrough',
    category: 'research',
    severity: 'informational',
    title: 'Research Breakthrough Achieved',
    summaryTemplate: '{techName} research completed',
    detailsTemplate: 'Research division has completed development of {techName}. Benefits: {benefits}. Unlocked projects: {unlockedProjects}. Next recommended research: {recommendedTech}.',
    triggerType: 'event_detected',
    sourceEntityType: 'research_division',
    baseConfidence: 1.0,
    actionable: false,
    cooldownMinutes: 0,
  },
  {
    id: 'expansion-colony-opportunity',
    category: 'expansion',
    severity: 'advisory',
    title: 'Colonization Opportunity',
    summaryTemplate: 'Suitable colony world found in {sector}',
    detailsTemplate: 'Scouts have identified a {planetType} world in the {sector} sector with {habitability}% habitability. Available resources: {resources}. Strategic value: {strategicValue}. Estimated colonization cost: {colonizationCost}.',
    triggerType: 'event_detected',
    sourceEntityType: 'sensor_network',
    baseConfidence: 0.75,
    actionable: true,
    cooldownMinutes: 120,
  },
  {
    id: 'internal-faction-unrest',
    category: 'internal',
    severity: 'warning',
    title: 'Internal Faction Unrest',
    summaryTemplate: '{factionName} showing signs of unrest',
    detailsTemplate: 'The {factionName} faction has {unrestLevel} unrest (threshold: {threshold}). Current approval: {approval}%. Recent grievances: {grievances}. Stability impact: {stabilityImpact}. Recommended actions: {recommendations}.',
    triggerType: 'threshold_exceeded',
    sourceEntityType: 'internal_affairs',
    baseConfidence: 0.8,
    actionable: true,
    cooldownMinutes: 60,
  },
  {
    id: 'threat-boss-emergence',
    category: 'threat',
    severity: 'urgent',
    title: 'Hostile Entity Emergence',
    summaryTemplate: 'Powerful hostile entity detected in {sector}',
    detailsTemplate: 'A {entityClass} class hostile entity has been detected in the {sector} sector. Estimated threat level: {threatLevel}. Combat rating: {combatRating}. Immediate response recommended. Nearby fleet assets: {nearbyAssets}.',
    triggerType: 'system_alert',
    sourceEntityType: 'sensor_network',
    baseConfidence: 0.9,
    actionable: true,
    cooldownMinutes: 60,
  },
  {
    id: 'strategic-opportunity',
    category: 'strategic',
    severity: 'advisory',
    title: 'Strategic Opportunity Identified',
    summaryTemplate: 'Strategic opportunity in {sector}',
    detailsTemplate: 'Analysis indicates a strategic opportunity in the {sector} region. {targetName} is currently weakened ({condition}) and vulnerable. Projected gains: {projectedGains}. Risks: {risks}. Success probability: {probability}%.',
    triggerType: 'system_alert',
    sourceEntityType: 'strategic_command',
    baseConfidence: 0.65,
    actionable: true,
    cooldownMinutes: 180,
  },
];

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

export function getReportCategoryConfig(category: AICReportCategory): AICReportCategoryConfig | undefined {
  return AIC_REPORT_CATEGORIES.find(c => c.category === category);
}

export function getReportSeverityConfig(severity: AICReportSeverity): AICReportSeverityConfig | undefined {
  return AIC_REPORT_SEVERITIES.find(s => s.severity === severity);
}

export function getReportTemplate(templateId: string): AICReportTemplate | undefined {
  return AIC_REPORT_TEMPLATES.find(t => t.id === templateId);
}

export function getReportTemplatesByCategory(category: AICReportCategory): readonly AICReportTemplate[] {
  return AIC_REPORT_TEMPLATES.filter(t => t.category === category);
}

export function getReportsBySeverity(severity: AICReportSeverity, reports: readonly AICReportData[]): readonly AICReportData[] {
  return reports.filter(r => r.severity === severity);
}

export function getActiveReports(reports: readonly AICReportData[]): readonly AICReportData[] {
  const now = Date.now();
  return reports.filter(r =>
    r.status === 'pending' &&
    (!r.expiryTimestamp || r.expiryTimestamp > now)
  );
}

export function generateReportId(): string {
  return `aic-rpt-${Date.now()}-${Math.random().toString(36).substring(2, 8)}`;
}

export function createAICReport(
  templateId: string,
  category: AICReportCategory,
  severity: AICReportSeverity,
  source: AICReportSource,
  title: string,
  summary: string,
  details: string,
  confidence?: number,
  relatedEntityId?: string,
  relatedEntityType?: string,
): AICReportData {
  const template = getReportTemplate(templateId);
  const categoryConfig = getReportCategoryConfig(category);
  const severityConfig = getReportSeverityConfig(severity);

  const retentionDays = categoryConfig?.defaultRetentionDays ?? 14;

  return {
    id: generateReportId(),
    category,
    severity,
    status: 'pending',
    trigger: template?.triggerType ?? 'system_alert',
    timestamp: Date.now(),
    title,
    summary,
    details,
    source,
    relatedEntityId,
    relatedEntityType,
    confidence: confidence ?? template?.baseConfidence ?? 0.5,
    recommendations: [],
    actionable: template?.actionable ?? false,
    expiryTimestamp: Date.now() + retentionDays * 24 * 60 * 60 * 1000,
  };
}
