-- Resources Seed Data
-- 30 resources from basic to exotic, covering all categories and tiers

INSERT INTO resources (name, description, category, tier, base_value, stack_limit, mining_difficulty, is_tradeable, is_market_listed, is_used_in_construction, is_used_in_research, is_used_in_manufacturing, is_used_in_shipbuilding, is_fuel, short_code) VALUES
('Metal Ore', 'Common iron and nickel ore. The backbone of all construction.', 'basic', 't1', 1.0, 999999999, 1, true, true, true, false, true, true, false, 'METAL'),
('Crystal', 'Silicon and rare earth crystals used in electronics and shielding.', 'basic', 't1', 2.0, 999999999, 2, true, true, true, true, true, true, false, 'CRYSTAL'),
('Deuterium', 'Hydrogen isotope used as fusion fuel and starship propellant.', 'basic', 't1', 4.0, 999999999, 3, true, true, true, false, true, true, true, 'DEUT'),
('Energy', 'Electrical power generated by reactors and solar arrays.', 'basic', 't1', 0.5, 999999999, 1, false, false, false, false, false, false, false, 'ENERGY'),
('Credits', 'Universal digital currency accepted across known space.', 'currency', 't1', 1.0, 999999999, 0, true, true, false, false, false, false, false, 'CRED'),
('Dark Matter', 'Exotic matter harvested from gravitational anomalies. Used in advanced research.', 'exotic', 't7', 500.0, 999999, 9, true, false, true, true, true, true, true, 'D_MATTER'),
('Titanium Alloy', 'Reinforced metal compound used in ship armor and structural elements.', 'refined', 't2', 5.0, 99999999, 3, true, true, true, false, true, true, false, 'TITAN'),
('Quantum Circuits', 'Advanced computational components for ship systems and AI cores.', 'refined', 't3', 25.0, 9999999, 4, true, true, false, true, true, true, false, 'QCIRC'),
('Antimatter', 'Extremely volatile energy source. A few grams can power a city for years.', 'advanced', 't4', 100.0, 999999, 7, true, false, false, true, true, false, true, 'AMATTER'),
('Plasma Cells', 'Contained fusion plasma used for weapons and propulsion.', 'advanced', 't3', 30.0, 9999999, 5, true, true, false, false, true, true, true, 'PLASMA'),
('Nanites', 'Microscopic repair and construction bots. Essential for high-tech manufacturing.', 'advanced', 't4', 75.0, 9999999, 6, true, true, false, true, true, true, false, 'NANITE'),
('Tritanium', 'Ultra-dense crystalline metal formed in neutron star collisions.', 'rare', 't5', 250.0, 999999, 7, true, true, true, false, true, true, false, 'TRIT'),
('Duranium', 'Super-strong alloy used in capital ship construction.', 'rare', 't5', 200.0, 999999, 7, true, true, true, false, true, true, false, 'DURAN'),
('Element Zero', 'Rare element that can manipulate mass when electrically charged.', 'exotic', 't6', 500.0, 99999, 8, true, false, false, true, true, true, false, 'E0'),
('Null Matter', 'Material from the void between universes. Nullifies energy fields.', 'exotic', 't7', 1000.0, 9999, 9, true, false, false, true, true, false, false, 'NULL'),
('Chronoton Particles', 'Temporal particles that allow manipulation of local time flow.', 'exotic', 't8', 5000.0, 999, 10, false, false, false, true, false, false, false, 'CHRON'),
('Neutronium', 'Ultra-dense matter from collapsed stars. Nearly indestructible.', 'rare', 't6', 500.0, 99999, 9, true, true, true, false, true, true, false, 'NEUTR'),
('Solarite', 'Crystalline mineral that absorbs and stores stellar energy.', 'advanced', 't3', 40.0, 9999999, 5, true, true, true, true, true, true, false, 'SOLAR'),
('Promethium', 'Radioactive element used in advanced weapons and reactors.', 'advanced', 't4', 80.0, 999999, 6, true, false, true, true, true, false, false, 'PROM'),
('Aetheric Dust', 'Remains of ancient spacecraft from before recorded history.', 'special', 't5', 300.0, 99999, 8, true, false, false, true, false, false, false, 'AETH'),
('Bio-Gel', 'Genetically engineered organic compound for medical and biological research.', 'special', 't3', 45.0, 999999, 4, true, true, false, true, false, false, false, 'BIOM'),
('Omega Particles', 'Extremely rare particles that enhance shield and weapon performance.', 'exotic', 't7', 2000.0, 9999, 10, true, false, false, true, true, true, false, 'OMEGA'),
('Hyperium', 'Metastable material that exists in multiple quantum states simultaneously.', 'exotic', 't6', 750.0, 99999, 8, true, false, true, true, true, true, false, 'HYPER'),
('Stygian Crystal', 'Black crystals that absorb all forms of energy. Used in stealth technology.', 'rare', 't5', 350.0, 999999, 7, true, false, false, true, true, true, false, 'STYG'),
('Computronium', 'Perfect computing substrate. A gram can simulate entire civilizations.', 'exotic', 't8', 10000.0, 99, 10, false, false, false, true, false, false, false, 'CPUTE'),
('Lumen Dust', 'Bioluminescent powder used in holographic displays and communications.', 'special', 't2', 15.0, 99999999, 3, true, true, false, false, false, false, false, 'LUMEN'),
('Phased Arrays', 'Quantum-linked components for FTL communication networks.', 'refined', 't4', 60.0, 9999999, 5, true, true, false, true, true, true, false, 'PHASED'),
('Polymers', 'Synthetic molecular compounds used in various manufacturing processes.', 'basic', 't2', 3.0, 999999999, 2, true, true, true, false, true, true, false, 'POLYM'),
('Ceramic Plating', 'Heat-resistant composite material for ship hulls and building exteriors.', 'refined', 't2', 8.0, 99999999, 2, true, true, true, false, true, true, false, 'CERAM'),
('Gravitic Lenses', 'Focusing arrays for gravity-based weapons and propulsion systems.', 'advanced', 't4', 90.0, 9999999, 6, true, true, false, true, true, true, false, 'GRAVL');

COMMENT ON TABLE resources IS 'Seed data: 30 resources across all categories and tiers with economy and usage flags';
