import { type EmpireStatCategory } from './empireStatsConfig';

export interface StatSource {
  type: 'technology' | 'commander' | 'building' | 'species' | 'item' | 'research' | 'planet' | 'formation' | 'innate';
  label: string;
  weight: number;
}

export interface StatMetadata {
  id: string;
  name: string;
  description: string;
  category: EmpireStatCategory;
  subCategory: string;
  displayGroup: string;
  isPercentage: boolean;
  isMillable: boolean;
  minValue: number;
  maxValue: number;
  defaultBase: number;
  sources: StatSource[];
  scaling: {
    type: 'linear' | 'diminishing' | 'exponential' | 'step';
    factorPerLevel: number;
    denominator?: number;
  };
  tags: string[];
}

export const STAT_METADATA: Record<string, StatMetadata> = {
  // ===== FLEET FIREPOWER =====
  attackPower: {
    id: 'attackPower',
    name: 'Attack Power',
    description: 'Base offensive capability of the fleet. Multiplied by efficiency and bonuses to produce final damage output.',
    category: 'fleet',
    subCategory: 'firepower',
    displayGroup: 'Fleet Firepower',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 99999,
    defaultBase: 10,
    sources: [
      { type: 'technology', label: 'Weapon Technology', weight: 0.4 },
      { type: 'commander', label: 'Military Command', weight: 0.3 },
      { type: 'building', label: 'Shipyard Level', weight: 0.2 },
      { type: 'innate', label: 'Fleet Composition', weight: 0.1 },
    ],
    scaling: { type: 'linear', factorPerLevel: 5 },
    tags: ['offense', 'fleet', 'core'],
  },
  weaponSystemsBonus: {
    id: 'weaponSystemsBonus',
    name: 'Weapon Systems',
    description: 'Percentage bonus to all weapon damage from advanced weapons research and ship module upgrades.',
    category: 'fleet',
    subCategory: 'firepower',
    displayGroup: 'Fleet Firepower',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 500,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Weapon Upgrades', weight: 0.5 },
      { type: 'research', label: 'Energy Weapons Research', weight: 0.3 },
      { type: 'item', label: 'Weapon Modules', weight: 0.2 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 3, denominator: 200 },
    tags: ['offense', 'weapon', 'percentage'],
  },
  attackSpeed: {
    id: 'attackSpeed',
    name: 'Fleet Attack Speed',
    description: 'Time in seconds between fleet volleys. Lower values mean faster attacks and more damage per combat round.',
    category: 'fleet',
    subCategory: 'firepower',
    displayGroup: 'Fleet Firepower',
    isPercentage: false,
    isMillable: false,
    minValue: 0.1,
    maxValue: 10,
    defaultBase: 1.0,
    sources: [
      { type: 'technology', label: 'Fire Control', weight: 0.4 },
      { type: 'commander', label: 'Military Command', weight: 0.3 },
      { type: 'formation', label: 'Combat Formation', weight: 0.3 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: -0.02, denominator: 50 },
    tags: ['offense', 'speed', 'time'],
  },
  combatEfficiency: {
    id: 'combatEfficiency',
    name: 'Combat Efficiency',
    description: 'Overall combat effectiveness multiplier. Affects all damage dealt. Derived from commander skills, fleet coordination, and morale.',
    category: 'fleet',
    subCategory: 'firepower',
    displayGroup: 'Fleet Firepower',
    isPercentage: true,
    isMillable: true,
    minValue: 50,
    maxValue: 300,
    defaultBase: 100,
    sources: [
      { type: 'commander', label: 'Tactical Skill', weight: 0.4 },
      { type: 'technology', label: 'Combat AI', weight: 0.3 },
      { type: 'innate', label: 'Fleet Morale', weight: 0.2 },
      { type: 'formation', label: 'Formation Bonus', weight: 0.1 },
    ],
    scaling: { type: 'linear', factorPerLevel: 2 },
    tags: ['offense', 'efficiency', 'multiplier'],
  },
  engagementRange: {
    id: 'engagementRange',
    name: 'Fleet Engagement Range',
    description: 'Maximum effective combat range in Astronomical Units (AU). Longer range allows first-strike capability and safer kiting.',
    category: 'fleet',
    subCategory: 'firepower',
    displayGroup: 'Fleet Firepower',
    isPercentage: false,
    isMillable: false,
    minValue: 0.5,
    maxValue: 100,
    defaultBase: 1.0,
    sources: [
      { type: 'technology', label: 'Weapon Range Tech', weight: 0.5 },
      { type: 'commander', label: 'Sensor Operations', weight: 0.3 },
      { type: 'item', label: 'Range Modules', weight: 0.2 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 0.08 },
    tags: ['offense', 'range', 'tactical'],
  },
  sensorRangeBonus: {
    id: 'sensorRangeBonus',
    name: 'Sensor Range Bonus',
    description: 'Additional sensor detection range percentage. Improves target acquisition and reduces enemy ambush effectiveness.',
    category: 'fleet',
    subCategory: 'firepower',
    displayGroup: 'Fleet Firepower',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 200,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Sensor Tech', weight: 0.5 },
      { type: 'commander', label: 'Sensor Operations', weight: 0.3 },
      { type: 'building', label: 'Observatory Level', weight: 0.2 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 2, denominator: 150 },
    tags: ['sensor', 'detection', 'range'],
  },
  speciesCombatBonus: {
    id: 'speciesCombatBonus',
    name: 'Species Combat Bonus',
    description: 'Racial/species innate combat bonus. Varies by empire species choice. Affects all offensive and defensive calculations.',
    category: 'fleet',
    subCategory: 'firepower',
    displayGroup: 'Fleet Firepower',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 200,
    defaultBase: 0,
    sources: [
      { type: 'species', label: 'Species Trait', weight: 0.8 },
      { type: 'technology', label: 'Genetic Engineering', weight: 0.2 },
    ],
    scaling: { type: 'linear', factorPerLevel: 0 },
    tags: ['species', 'innate', 'combat'],
  },

  // ===== FLEET ACCURACY =====
  fleetAccuracy: {
    id: 'fleetAccuracy',
    name: 'Fleet Accuracy',
    description: 'Base hit chance modifier for all fleet weapons. Higher values mean more shots land on target.',
    category: 'fleet',
    subCategory: 'accuracy',
    displayGroup: 'Fleet Accuracy',
    isPercentage: false,
    isMillable: true,
    minValue: 10,
    maxValue: 99999,
    defaultBase: 100,
    sources: [
      { type: 'technology', label: 'Targeting Systems', weight: 0.4 },
      { type: 'commander', label: 'Sensor Operations', weight: 0.3 },
      { type: 'building', label: 'Fire Control Center', weight: 0.2 },
      { type: 'formation', label: 'Formation Accuracy', weight: 0.1 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.15 },
    tags: ['offense', 'accuracy', 'targeting'],
  },
  missileAccuracy: {
    id: 'missileAccuracy',
    name: 'Missile Accuracy',
    description: 'Hit chance specifically for missile-type weapons. Affected by countermeasures and ECM.',
    category: 'fleet',
    subCategory: 'accuracy',
    displayGroup: 'Fleet Accuracy',
    isPercentage: false,
    isMillable: true,
    minValue: 10,
    maxValue: 99999,
    defaultBase: 80,
    sources: [
      { type: 'technology', label: 'Missile Tech', weight: 0.5 },
      { type: 'commander', label: 'Tactical Skill', weight: 0.3 },
      { type: 'item', label: 'Guidance Modules', weight: 0.2 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.1 },
    tags: ['offense', 'missile', 'accuracy'],
  },
  energyWeaponAccuracy: {
    id: 'energyWeaponAccuracy',
    name: 'Energy Weapon Accuracy',
    description: 'Hit chance specifically for energy-based weapons (lasers, plasma, ion). Less affected by ECM.',
    category: 'fleet',
    subCategory: 'accuracy',
    displayGroup: 'Fleet Accuracy',
    isPercentage: false,
    isMillable: true,
    minValue: 10,
    maxValue: 99999,
    defaultBase: 80,
    sources: [
      { type: 'technology', label: 'Energy Weapon Tech', weight: 0.5 },
      { type: 'commander', label: 'Sensor Operations', weight: 0.3 },
      { type: 'building', label: 'Focusing Array', weight: 0.2 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.1 },
    tags: ['offense', 'energy', 'accuracy'],
  },
  commanderTargetingBonus: {
    id: 'commanderTargetingBonus',
    name: 'Commander Targeting Bonus',
    description: 'Flat accuracy bonus applied from commander targeting skills and sensor operation expertise.',
    category: 'fleet',
    subCategory: 'accuracy',
    displayGroup: 'Fleet Accuracy',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 0,
    sources: [
      { type: 'commander', label: 'Sensor Operations', weight: 0.6 },
      { type: 'commander', label: 'Tactical Skill', weight: 0.4 },
    ],
    scaling: { type: 'linear', factorPerLevel: 5 },
    tags: ['commander', 'accuracy', 'bonus'],
  },

  // ===== CRITICAL STRIKE =====
  fleetCriticalChance: {
    id: 'fleetCriticalChance',
    name: 'Fleet Critical Chance',
    description: 'Overall percentage chance for fleet weapons to score a critical hit, dealing bonus damage.',
    category: 'fleet',
    subCategory: 'critical',
    displayGroup: 'Critical Strike Systems',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 95,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Critical Hit Tech', weight: 0.4 },
      { type: 'commander', label: 'Tactical Skill', weight: 0.3 },
      { type: 'item', label: 'Targeting Modules', weight: 0.2 },
      { type: 'innate', label: 'Species Bonus', weight: 0.1 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.5, denominator: 100 },
    tags: ['offense', 'critical', 'chance'],
  },
  missileCriticalChance: {
    id: 'missileCriticalChance',
    name: 'Missile Critical Chance',
    description: 'Critical hit chance specifically for missile weapons. Often higher than energy crit chance but more affected by point defense.',
    category: 'fleet',
    subCategory: 'critical',
    displayGroup: 'Critical Strike Systems',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 95,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Warhead Tech', weight: 0.5 },
      { type: 'commander', label: 'Tactical Skill', weight: 0.3 },
      { type: 'item', label: 'Guidance Upgrade', weight: 0.2 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.4, denominator: 100 },
    tags: ['offense', 'critical', 'missile'],
  },
  energyCriticalChance: {
    id: 'energyCriticalChance',
    name: 'Energy Critical Chance',
    description: 'Critical hit chance for energy weapons. Gains bonus from focusing tech and capacitor stability.',
    category: 'fleet',
    subCategory: 'critical',
    displayGroup: 'Critical Strike Systems',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 95,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Focusing Tech', weight: 0.5 },
      { type: 'commander', label: 'Engineering', weight: 0.3 },
      { type: 'building', label: 'Capacitor Array', weight: 0.2 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.4, denominator: 100 },
    tags: ['offense', 'critical', 'energy'],
  },
  fleetHeavyStrike: {
    id: 'fleetHeavyStrike',
    name: 'Fleet Heavy Strike',
    description: 'Chance to perform a devastating heavy strike that ignores a portion of enemy armor and shields.',
    category: 'fleet',
    subCategory: 'critical',
    displayGroup: 'Critical Strike Systems',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 95,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Heavy Ordnance', weight: 0.4 },
      { type: 'commander', label: 'Military Command', weight: 0.3 },
      { type: 'item', label: 'Siege Modules', weight: 0.3 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.6, denominator: 100 },
    tags: ['offense', 'heavy', 'penetration'],
  },
  missileHeavyStrike: {
    id: 'missileHeavyStrike',
    name: 'Missile Heavy Strike',
    description: 'Heavy strike chance for missile weapons. Torpedo and siege missile variants excel at this.',
    category: 'fleet',
    subCategory: 'critical',
    displayGroup: 'Critical Strike Systems',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 95,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Torpedo Tech', weight: 0.5 },
      { type: 'commander', label: 'Tactical Skill', weight: 0.3 },
      { type: 'item', label: 'Heavy Warheads', weight: 0.2 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.5, denominator: 100 },
    tags: ['offense', 'heavy', 'missile'],
  },
  energyHeavyStrike: {
    id: 'energyHeavyStrike',
    name: 'Energy Heavy Strike',
    description: 'Heavy strike chance for energy weapons. Overcharged capacitor shots can bypass shields partially.',
    category: 'fleet',
    subCategory: 'critical',
    displayGroup: 'Critical Strike Systems',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 95,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Overcharge Tech', weight: 0.5 },
      { type: 'commander', label: 'Engineering', weight: 0.3 },
      { type: 'building', label: 'Capacitor Bank', weight: 0.2 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.5, denominator: 100 },
    tags: ['offense', 'heavy', 'energy'],
  },
  criticalDamageBonus: {
    id: 'criticalDamageBonus',
    name: 'Critical Damage Bonus',
    description: 'Additional damage multiplier applied when a critical hit lands. Stacks multiplicatively with other damage bonuses.',
    category: 'fleet',
    subCategory: 'critical',
    displayGroup: 'Critical Strike Systems',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 500,
    defaultBase: 50,
    sources: [
      { type: 'technology', label: 'Critical Amplifier', weight: 0.4 },
      { type: 'commander', label: 'Tactical Skill', weight: 0.3 },
      { type: 'item', label: 'Focus Crystals', weight: 0.3 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 2, denominator: 250 },
    tags: ['offense', 'critical', 'damage'],
  },
  heavyStrikeDamage: {
    id: 'heavyStrikeDamage',
    name: 'Heavy Strike Damage',
    description: 'Bonus damage specifically for heavy strikes. Heavy strikes already bypass defenses, and this increases their raw power.',
    category: 'fleet',
    subCategory: 'critical',
    displayGroup: 'Critical Strike Systems',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 500,
    defaultBase: 25,
    sources: [
      { type: 'technology', label: 'Siege Tech', weight: 0.4 },
      { type: 'commander', label: 'Military Command', weight: 0.3 },
      { type: 'building', label: 'Ordnance Factory', weight: 0.3 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 1.5, denominator: 250 },
    tags: ['offense', 'heavy', 'damage'],
  },

  // ===== FLEET DEFENSE =====
  fleetArmor: {
    id: 'fleetArmor',
    name: 'Fleet Armor',
    description: 'Base armor rating of the fleet. Reduces incoming damage through ablative absorption. Higher armor means more damage mitigated.',
    category: 'fleet',
    subCategory: 'defense',
    displayGroup: 'Fleet Defense',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 99999,
    defaultBase: 50,
    sources: [
      { type: 'technology', label: 'Armor Tech', weight: 0.4 },
      { type: 'building', label: 'Armor Foundry', weight: 0.3 },
      { type: 'commander', label: 'Engineering', weight: 0.2 },
      { type: 'species', label: 'Species Trait', weight: 0.1 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.12 },
    tags: ['defense', 'armor', 'core'],
  },
  shieldRating: {
    id: 'shieldRating',
    name: 'Shield Rating',
    description: 'Energy shield capacity of the fleet. Shields absorb incoming damage before it reaches the hull. Regenerates over time.',
    category: 'fleet',
    subCategory: 'defense',
    displayGroup: 'Fleet Defense',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 99999,
    defaultBase: 50,
    sources: [
      { type: 'technology', label: 'Shield Tech', weight: 0.4 },
      { type: 'building', label: 'Shield Generator', weight: 0.3 },
      { type: 'commander', label: 'Engineering', weight: 0.2 },
      { type: 'item', label: 'Shield Modules', weight: 0.1 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.12 },
    tags: ['defense', 'shield', 'core'],
  },
  energyShield: {
    id: 'energyShield',
    name: 'Energy Shield',
    description: 'Specialized energy shield layer that is particularly effective against energy weapons but weaker against kinetic. Supplementary to main shields.',
    category: 'fleet',
    subCategory: 'defense',
    displayGroup: 'Fleet Defense',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 99999,
    defaultBase: 20,
    sources: [
      { type: 'technology', label: 'Energy Shield Tech', weight: 0.5 },
      { type: 'building', label: 'Shield Amplifier', weight: 0.3 },
      { type: 'commander', label: 'Engineering', weight: 0.2 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.1 },
    tags: ['defense', 'shield', 'energy'],
  },
  hullDamageReduction: {
    id: 'hullDamageReduction',
    name: 'Hull Damage Reduction',
    description: 'Flat damage reduction applied to all incoming hull damage. Each point reduces incoming damage by 1, before percentage mitigation.',
    category: 'fleet',
    subCategory: 'defense',
    displayGroup: 'Fleet Defense',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 999,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Hull Reinforcement', weight: 0.5 },
      { type: 'building', label: 'Nanite Repair Bay', weight: 0.3 },
      { type: 'species', label: 'Natural Armor', weight: 0.2 },
    ],
    scaling: { type: 'linear', factorPerLevel: 1 },
    tags: ['defense', 'hull', 'mitigation'],
  },
  criticalDamageResistance: {
    id: 'criticalDamageResistance',
    name: 'Critical Damage Resistance',
    description: 'Percentage reduction to bonus damage received from enemy critical hits. High resistance makes enemy crits less punishing.',
    category: 'fleet',
    subCategory: 'defense',
    displayGroup: 'Fleet Defense',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 90,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Reinforced Hull', weight: 0.4 },
      { type: 'commander', label: 'Engineering', weight: 0.3 },
      { type: 'item', label: 'Ablative Plating', weight: 0.3 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.4, denominator: 150 },
    tags: ['defense', 'critical', 'resistance'],
  },
  heavyStrikeResistance: {
    id: 'heavyStrikeResistance',
    name: 'Heavy Strike Resistance',
    description: 'Reduces the chance and damage of enemy heavy strikes against your fleet. Heavy strikes that are resisted deal reduced penetration.',
    category: 'fleet',
    subCategory: 'defense',
    displayGroup: 'Fleet Defense',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 90,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Reactive Armor', weight: 0.4 },
      { type: 'commander', label: 'Engineering', weight: 0.3 },
      { type: 'building', label: 'Armor Reinforcement', weight: 0.3 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.5, denominator: 150 },
    tags: ['defense', 'heavy', 'resistance'],
  },
  fleetDamageResistance: {
    id: 'fleetDamageResistance',
    name: 'Fleet Damage Resistance',
    description: 'Overall damage resistance percentage for the fleet. Applies after armor and shield calculations as a final damage multiplier.',
    category: 'fleet',
    subCategory: 'defense',
    displayGroup: 'Fleet Defense',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 90,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Composite Armor', weight: 0.3 },
      { type: 'commander', label: 'Engineering', weight: 0.3 },
      { type: 'formation', label: 'Defensive Formation', weight: 0.2 },
      { type: 'species', label: 'Species Trait', weight: 0.2 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.3, denominator: 100 },
    tags: ['defense', 'resistance', 'mitigation'],
  },

  // ===== EVASION =====
  fleetEvasion: {
    id: 'fleetEvasion',
    name: 'Fleet Evasion',
    description: 'Overall chance for fleet ships to evade incoming attacks. Affected by ship speed, commander skills, and electronic warfare.',
    category: 'fleet',
    subCategory: 'evasion',
    displayGroup: 'Evasion Systems',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 95,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Propulsion Tech', weight: 0.3 },
      { type: 'commander', label: 'Tactical Skill', weight: 0.3 },
      { type: 'item', label: 'ECM Modules', weight: 0.2 },
      { type: 'formation', label: 'Evasion Formation', weight: 0.2 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.5, denominator: 80 },
    tags: ['defense', 'evasion', 'mobility'],
  },
  missileEvasion: {
    id: 'missileEvasion',
    name: 'Missile Evasion',
    description: 'Evasion chance specifically against missile attacks. Point defense systems and countermeasures contribute here.',
    category: 'fleet',
    subCategory: 'evasion',
    displayGroup: 'Evasion Systems',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 95,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Point Defense', weight: 0.4 },
      { type: 'item', label: 'Flare Launchers', weight: 0.3 },
      { type: 'commander', label: 'Tactical Skill', weight: 0.3 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.4, denominator: 80 },
    tags: ['defense', 'evasion', 'missile'],
  },
  energyWeaponEvasion: {
    id: 'energyWeaponEvasion',
    name: 'Energy Weapon Evasion',
    description: 'Evasion chance against energy weapons. Shield modulation and heat dissipation techniques help reduce energy weapon accuracy.',
    category: 'fleet',
    subCategory: 'evasion',
    displayGroup: 'Evasion Systems',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 95,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Shield Modulation', weight: 0.4 },
      { type: 'commander', label: 'Engineering', weight: 0.3 },
      { type: 'item', label: 'Heat Sinks', weight: 0.3 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.4, denominator: 80 },
    tags: ['defense', 'evasion', 'energy'],
  },
  heavyStrikeEvasion: {
    id: 'heavyStrikeEvasion',
    name: 'Heavy Strike Evasion',
    description: 'Chance to evade heavy strikes entirely. Heavy strikes are slower and telegraphed, making them easier to dodge with good piloting.',
    category: 'fleet',
    subCategory: 'evasion',
    displayGroup: 'Evasion Systems',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 95,
    defaultBase: 0,
    sources: [
      { type: 'commander', label: 'Tactical Skill', weight: 0.4 },
      { type: 'technology', label: 'Advanced Piloting', weight: 0.3 },
      { type: 'formation', label: 'Scatter Formation', weight: 0.3 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.3, denominator: 80 },
    tags: ['defense', 'evasion', 'heavy'],
  },
  rearAssaultAvoidance: {
    id: 'rearAssaultAvoidance',
    name: 'Rear Assault Avoidance',
    description: 'Chance to avoid or mitigate damage from rear attacks. Flanking maneuvers are less effective against fleets with high rear assault avoidance.',
    category: 'fleet',
    subCategory: 'evasion',
    displayGroup: 'Evasion Systems',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 95,
    defaultBase: 0,
    sources: [
      { type: 'commander', label: 'Tactical Skill', weight: 0.4 },
      { type: 'technology', label: 'Sensor Net', weight: 0.3 },
      { type: 'formation', label: 'Defensive Perimeter', weight: 0.3 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.3, denominator: 100 },
    tags: ['defense', 'evasion', 'tactical'],
  },

  // ===== COMMANDER =====
  militaryCommand: {
    id: 'militaryCommand',
    name: 'Military Command',
    description: 'Commander aptitude for fleet combat and military operations. Increases fleet attack power, attack speed, and heavy strike effectiveness.',
    category: 'empire',
    subCategory: 'commander',
    displayGroup: 'Commander Statistics',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 999,
    defaultBase: 1,
    sources: [
      { type: 'commander', label: 'Command Skill', weight: 0.6 },
      { type: 'technology', label: 'Military Science', weight: 0.3 },
      { type: 'innate', label: 'Species Bonus', weight: 0.1 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.1 },
    tags: ['commander', 'offense', 'command'],
  },
  engineering: {
    id: 'engineering',
    name: 'Engineering',
    description: 'Commander engineering aptitude. Improves fleet defenses, shield capacity, repair efficiency, and building speed.',
    category: 'empire',
    subCategory: 'commander',
    displayGroup: 'Commander Statistics',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 999,
    defaultBase: 1,
    sources: [
      { type: 'commander', label: 'Engineering Skill', weight: 0.6 },
      { type: 'technology', label: 'Engineering Tech', weight: 0.3 },
      { type: 'innate', label: 'Species Bonus', weight: 0.1 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.1 },
    tags: ['commander', 'defense', 'production'],
  },
  scientificResearch: {
    id: 'scientificResearch',
    name: 'Scientific Research',
    description: 'Commander aptitude for scientific research. Increases research speed, technology cooldown reduction, and unlocks advanced tech.',
    category: 'empire',
    subCategory: 'commander',
    displayGroup: 'Commander Statistics',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 999,
    defaultBase: 1,
    sources: [
      { type: 'commander', label: 'Science Skill', weight: 0.6 },
      { type: 'technology', label: 'Research Lab', weight: 0.3 },
      { type: 'innate', label: 'Species Bonus', weight: 0.1 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.1 },
    tags: ['commander', 'science', 'technology'],
  },
  sensorOperations: {
    id: 'sensorOperations',
    name: 'Sensor Operations',
    description: 'Commander sensor aptitude. Improves fleet accuracy, detection range, and resistance to sensor jamming.',
    category: 'empire',
    subCategory: 'commander',
    displayGroup: 'Commander Statistics',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 999,
    defaultBase: 1,
    sources: [
      { type: 'commander', label: 'Sensor Skill', weight: 0.6 },
      { type: 'technology', label: 'Sensor Tech', weight: 0.3 },
      { type: 'innate', label: 'Species Bonus', weight: 0.1 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.1 },
    tags: ['commander', 'sensor', 'accuracy'],
  },
  empireLogistics: {
    id: 'empireLogistics',
    name: 'Empire Logistics',
    description: 'Commander logistics aptitude. Improves resource production, population growth, energy efficiency, and trade effectiveness.',
    category: 'empire',
    subCategory: 'commander',
    displayGroup: 'Commander Statistics',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 999,
    defaultBase: 1,
    sources: [
      { type: 'commander', label: 'Logistics Skill', weight: 0.6 },
      { type: 'technology', label: 'Logistics Tech', weight: 0.3 },
      { type: 'innate', label: 'Species Bonus', weight: 0.1 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.1 },
    tags: ['commander', 'economy', 'logistics'],
  },

  // ===== EMPIRE RESOURCES =====
  maxPopulation: {
    id: 'maxPopulation',
    name: 'Maximum Population',
    description: 'Maximum population capacity across all colonies. Population generates resources and tax income. Tech and buildings increase cap.',
    category: 'empire',
    subCategory: 'resources',
    displayGroup: 'Empire Resources',
    isPercentage: false,
    isMillable: true,
    minValue: 100,
    maxValue: 9999999,
    defaultBase: 500,
    sources: [
      { type: 'building', label: 'Housing Complex', weight: 0.5 },
      { type: 'technology', label: 'Colonial Admin', weight: 0.3 },
      { type: 'planet', label: 'Planet Size', weight: 0.2 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.08 },
    tags: ['economy', 'population', 'resource'],
  },
  populationGrowth: {
    id: 'populationGrowth',
    name: 'Population Growth',
    description: 'Population increase per hour. Affected by available housing, food supply, and infrastructure. Higher growth means faster empire expansion.',
    category: 'empire',
    subCategory: 'resources',
    displayGroup: 'Empire Resources',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 99999,
    defaultBase: 10,
    sources: [
      { type: 'building', label: 'Habitat Dome', weight: 0.4 },
      { type: 'technology', label: 'Bio-Engineering', weight: 0.3 },
      { type: 'commander', label: 'Empire Logistics', weight: 0.2 },
      { type: 'species', label: 'Fecundity Trait', weight: 0.1 },
    ],
    scaling: { type: 'linear', factorPerLevel: 3 },
    tags: ['economy', 'population', 'growth'],
  },
  maxEnergy: {
    id: 'maxEnergy',
    name: 'Maximum Energy',
    description: 'Total energy capacity of the empire. Energy is used for fleet operations, building construction, and special abilities. Running out causes penalties.',
    category: 'empire',
    subCategory: 'resources',
    displayGroup: 'Empire Resources',
    isPercentage: false,
    isMillable: true,
    minValue: 100,
    maxValue: 999999,
    defaultBase: 500,
    sources: [
      { type: 'building', label: 'Power Plant', weight: 0.5 },
      { type: 'technology', label: 'Energy Tech', weight: 0.3 },
      { type: 'commander', label: 'Engineering', weight: 0.2 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.1 },
    tags: ['economy', 'energy', 'resource'],
  },
  energyRegeneration: {
    id: 'energyRegeneration',
    name: 'Energy Regeneration',
    description: 'Energy recovered per hour. Higher regeneration means fleets can operate longer and buildings can function at higher capacity.',
    category: 'empire',
    subCategory: 'resources',
    displayGroup: 'Empire Resources',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 99999,
    defaultBase: 20,
    sources: [
      { type: 'building', label: 'Generator Array', weight: 0.4 },
      { type: 'technology', label: 'Fusion Tech', weight: 0.3 },
      { type: 'commander', label: 'Engineering', weight: 0.2 },
      { type: 'species', label: 'Energy Symbiote', weight: 0.1 },
    ],
    scaling: { type: 'linear', factorPerLevel: 5 },
    tags: ['economy', 'energy', 'regen'],
  },
  energyEfficiency: {
    id: 'energyEfficiency',
    name: 'Energy Efficiency',
    description: 'Percentage bonus to all energy production and reduced energy consumption. Makes the entire empire more energy-efficient.',
    category: 'empire',
    subCategory: 'resources',
    displayGroup: 'Empire Resources',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 200,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Efficiency Tech', weight: 0.4 },
      { type: 'commander', label: 'Engineering', weight: 0.3 },
      { type: 'species', label: 'Efficient Metabolism', weight: 0.3 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.5, denominator: 100 },
    tags: ['economy', 'energy', 'efficiency'],
  },

  // ===== FLEET MOBILITY =====
  warpSpeedBonus: {
    id: 'warpSpeedBonus',
    name: 'Fleet Warp Speed Bonus',
    description: 'Percentage bonus to fleet warp speed. Faster warp means quicker response times and shorter travel between systems.',
    category: 'empire',
    subCategory: 'mobility',
    displayGroup: 'Fleet Mobility',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 500,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Warp Drive Tech', weight: 0.5 },
      { type: 'commander', label: 'Navigation Skill', weight: 0.3 },
      { type: 'building', label: 'Warp Gate', weight: 0.2 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 2, denominator: 150 },
    tags: ['mobility', 'warp', 'speed'],
  },
  maxWarpCapacity: {
    id: 'maxWarpCapacity',
    name: 'Maximum Warp Capacity',
    description: 'Maximum number of fleet units that can be warped simultaneously. Higher capacity allows moving larger fleets in a single warp.',
    category: 'empire',
    subCategory: 'mobility',
    displayGroup: 'Fleet Mobility',
    isPercentage: false,
    isMillable: true,
    minValue: 1,
    maxValue: 999,
    defaultBase: 5,
    sources: [
      { type: 'technology', label: 'Warp Physics', weight: 0.5 },
      { type: 'building', label: 'Warp Gate Array', weight: 0.3 },
      { type: 'commander', label: 'Navigation Skill', weight: 0.2 },
    ],
    scaling: { type: 'linear', factorPerLevel: 1 },
    tags: ['mobility', 'warp', 'capacity'],
  },
  warpRechargeRate: {
    id: 'warpRechargeRate',
    name: 'Warp Recharge Rate',
    description: 'Warp drive recharge rate per second. Determines how quickly the fleet can make consecutive warp jumps.',
    category: 'empire',
    subCategory: 'mobility',
    displayGroup: 'Fleet Mobility',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 100,
    defaultBase: 0.5,
    sources: [
      { type: 'technology', label: 'Warp Cooldown Tech', weight: 0.5 },
      { type: 'commander', label: 'Engineering', weight: 0.3 },
      { type: 'building', label: 'Warp Capacitor', weight: 0.2 },
    ],
    scaling: { type: 'linear', factorPerLevel: 0.05 },
    tags: ['mobility', 'warp', 'recharge'],
  },

  // ===== TECHNOLOGY =====
  researchEfficiency: {
    id: 'researchEfficiency',
    name: 'Research Efficiency',
    description: 'Percentage reduction in research time for all technologies. Higher efficiency means faster tech progression.',
    category: 'technology',
    subCategory: 'general',
    displayGroup: 'Technology',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 95,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Scientific Method', weight: 0.4 },
      { type: 'commander', label: 'Scientific Research', weight: 0.3 },
      { type: 'building', label: 'Research Lab', weight: 0.3 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.5, denominator: 100 },
    tags: ['technology', 'research', 'speed'],
  },
  technologyCooldownReduction: {
    id: 'technologyCooldownReduction',
    name: 'Technology Cooldown Reduction',
    description: 'Reduces the cooldown period after researching technologies. Allows chaining tech research more rapidly.',
    category: 'technology',
    subCategory: 'general',
    displayGroup: 'Technology',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 90,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Quantum Computing', weight: 0.4 },
      { type: 'commander', label: 'Scientific Research', weight: 0.3 },
      { type: 'building', label: 'Supercomputer', weight: 0.3 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.3, denominator: 100 },
    tags: ['technology', 'cooldown', 'speed'],
  },
  infrastructureEfficiency: {
    id: 'infrastructureEfficiency',
    name: 'Infrastructure Efficiency',
    description: 'Percentage bonus to building construction speed and upgrade speed. Makes empire expansion faster.',
    category: 'technology',
    subCategory: 'general',
    displayGroup: 'Technology',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 200,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Construction Tech', weight: 0.4 },
      { type: 'commander', label: 'Engineering', weight: 0.3 },
      { type: 'building', label: 'Construction Yard', weight: 0.3 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.5, denominator: 150 },
    tags: ['technology', 'infrastructure', 'building'],
  },
  buffDuration: {
    id: 'buffDuration',
    name: 'Buff Duration (Empire Effects)',
    description: 'Percentage increase to duration of all empire-wide buff effects. Includes combat buffs, production buffs, and defensive buffs.',
    category: 'technology',
    subCategory: 'general',
    displayGroup: 'Technology',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 300,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Temporal Physics', weight: 0.5 },
      { type: 'commander', label: 'Scientific Research', weight: 0.3 },
      { type: 'building', label: 'Chronal Stabilizer', weight: 0.2 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 1, denominator: 100 },
    tags: ['technology', 'buff', 'duration'],
  },
  enemyDebuffDuration: {
    id: 'enemyDebuffDuration',
    name: 'Enemy Debuff Duration',
    description: 'Negative percentage applied to enemy debuff duration on your empire. Reduces how long enemy EWAR and tactical debuffs last.',
    category: 'technology',
    subCategory: 'general',
    displayGroup: 'Technology',
    isPercentage: true,
    isMillable: true,
    minValue: -100,
    maxValue: 0,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Countermeasures', weight: 0.5 },
      { type: 'commander', label: 'Sensor Operations', weight: 0.3 },
      { type: 'building', label: 'ECM Tower', weight: 0.2 },
    ],
    scaling: { type: 'linear', factorPerLevel: -2 },
    tags: ['technology', 'debuff', 'defense'],
  },
  repairEfficiency: {
    id: 'repairEfficiency',
    name: 'Repair Efficiency',
    description: 'Percentage bonus to fleet repair speed. Faster repairs mean fleets return to combat more quickly after engagements.',
    category: 'technology',
    subCategory: 'general',
    displayGroup: 'Technology',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 200,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Nanite Repair', weight: 0.4 },
      { type: 'commander', label: 'Engineering', weight: 0.3 },
      { type: 'building', label: 'Repair Dock', weight: 0.3 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.5, denominator: 150 },
    tags: ['technology', 'repair', 'sustain'],
  },
  colonyHealingBonus: {
    id: 'colonyHealingBonus',
    name: 'Colony Healing Bonus',
    description: 'Percentage bonus to colony healing and recovery speed after attacks. Reduces the time colonies remain damaged.',
    category: 'technology',
    subCategory: 'general',
    displayGroup: 'Technology',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 200,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Terraforming', weight: 0.4 },
      { type: 'commander', label: 'Engineering', weight: 0.3 },
      { type: 'building', label: 'Medical Center', weight: 0.3 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.5, denominator: 150 },
    tags: ['technology', 'colony', 'healing'],
  },

  // ===== RESISTANCE =====
  empResistance: {
    id: 'empResistance',
    name: 'EMP Resistance',
    description: 'Resistance to electromagnetic pulse attacks. EMP attacks disable ship electronics and weapons temporarily. Higher resistance reduces duration and effect.',
    category: 'resistance',
    subCategory: 'electronicWarfare',
    displayGroup: 'Electronic Warfare Resistance',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 10,
    sources: [
      { type: 'technology', label: 'Hardened Electronics', weight: 0.4 },
      { type: 'commander', label: 'Engineering', weight: 0.3 },
      { type: 'item', label: 'EMP Shielding', weight: 0.3 },
    ],
    scaling: { type: 'linear', factorPerLevel: 8 },
    tags: ['resistance', 'ewar', 'emp'],
  },
  jammingResistance: {
    id: 'jammingResistance',
    name: 'Jamming Resistance',
    description: 'Resistance to sensor jamming and communications disruption. Jamming reduces fleet coordination and targeting effectiveness.',
    category: 'resistance',
    subCategory: 'electronicWarfare',
    displayGroup: 'Electronic Warfare Resistance',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 10,
    sources: [
      { type: 'technology', label: 'Frequency Hopping', weight: 0.4 },
      { type: 'commander', label: 'Sensor Operations', weight: 0.3 },
      { type: 'building', label: 'Comms Array', weight: 0.3 },
    ],
    scaling: { type: 'linear', factorPerLevel: 8 },
    tags: ['resistance', 'ewar', 'jamming'],
  },
  sensorBlindResistance: {
    id: 'sensorBlindResistance',
    name: 'Sensor Blind Resistance',
    description: 'Resistance to sensor blinding attacks. Sensor blinding reduces detection range and accuracy, making fleets vulnerable to ambushes.',
    category: 'resistance',
    subCategory: 'electronicWarfare',
    displayGroup: 'Electronic Warfare Resistance',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 10,
    sources: [
      { type: 'technology', label: 'Multi-Spectrum Sensors', weight: 0.4 },
      { type: 'commander', label: 'Sensor Operations', weight: 0.3 },
      { type: 'item', label: 'Sensor Filters', weight: 0.3 },
    ],
    scaling: { type: 'linear', factorPerLevel: 8 },
    tags: ['resistance', 'ewar', 'sensor'],
  },
  hackResistance: {
    id: 'hackResistance',
    name: 'Hack Resistance',
    description: 'Resistance to cyber hacking attacks. Hacks can steal research data, disrupt ship systems, or temporarily disable automated defense platforms.',
    category: 'resistance',
    subCategory: 'electronicWarfare',
    displayGroup: 'Electronic Warfare Resistance',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 10,
    sources: [
      { type: 'technology', label: 'Cyber Security', weight: 0.5 },
      { type: 'commander', label: 'Scientific Research', weight: 0.3 },
      { type: 'building', label: 'Data Vault', weight: 0.2 },
    ],
    scaling: { type: 'linear', factorPerLevel: 8 },
    tags: ['resistance', 'ewar', 'hack'],
  },
  communicationsResistance: {
    id: 'communicationsResistance',
    name: 'Communications Resistance',
    description: 'Resistance to communications interception and disruption. Protects fleet coordination, order transmission, and allied communication channels.',
    category: 'resistance',
    subCategory: 'electronicWarfare',
    displayGroup: 'Electronic Warfare Resistance',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 10,
    sources: [
      { type: 'technology', label: 'Encrypted Comms', weight: 0.4 },
      { type: 'commander', label: 'Sensor Operations', weight: 0.3 },
      { type: 'building', label: 'Quantum Relay', weight: 0.3 },
    ],
    scaling: { type: 'linear', factorPerLevel: 8 },
    tags: ['resistance', 'ewar', 'comms'],
  },
  panicResistance: {
    id: 'panicResistance',
    name: 'Panic Resistance',
    description: 'Resistance to fear and panic-inducing effects. Panic can cause fleet units to behave erratically, reduce combat efficiency, or trigger retreat.',
    category: 'resistance',
    subCategory: 'electronicWarfare',
    displayGroup: 'Electronic Warfare Resistance',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 10,
    sources: [
      { type: 'technology', label: 'Morale Enhancement', weight: 0.4 },
      { type: 'commander', label: 'Military Command', weight: 0.3 },
      { type: 'species', label: 'Stoic Nature', weight: 0.3 },
    ],
    scaling: { type: 'linear', factorPerLevel: 8 },
    tags: ['resistance', 'ewar', 'panic'],
  },
  tractorBeamResistance: {
    id: 'tractorBeamResistance',
    name: 'Tractor Beam Resistance',
    description: 'Resistance to tractor beam effects. Tractor beams can immobilize ships, prevent retreat, or pull ships out of formation. Has a higher base than other resistances.',
    category: 'resistance',
    subCategory: 'electronicWarfare',
    displayGroup: 'Electronic Warfare Resistance',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 50,
    sources: [
      { type: 'technology', label: 'Inertial Dampeners', weight: 0.4 },
      { type: 'commander', label: 'Engineering', weight: 0.3 },
      { type: 'item', label: 'Gravity Shields', weight: 0.3 },
    ],
    scaling: { type: 'linear', factorPerLevel: 10 },
    tags: ['resistance', 'ewar', 'tractor'],
  },
  collisionResistance: {
    id: 'collisionResistance',
    name: 'Collision Resistance',
    description: 'Resistance to collision-based attacks such as ramming or debris field collisions. Has the highest base resistance as it involves physical countermeasures.',
    category: 'resistance',
    subCategory: 'electronicWarfare',
    displayGroup: 'Electronic Warfare Resistance',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 100,
    sources: [
      { type: 'technology', label: 'Structural Integrity', weight: 0.4 },
      { type: 'commander', label: 'Engineering', weight: 0.3 },
      { type: 'item', label: 'Reinforced Hull Plating', weight: 0.3 },
    ],
    scaling: { type: 'linear', factorPerLevel: 12 },
    tags: ['resistance', 'ewar', 'collision'],
  },

  // ===== ELECTRONIC WARFARE =====
  empChance: {
    id: 'empChance',
    name: 'EMP Chance',
    description: 'Chance to successfully land an EMP attack on the target. EMP disables enemy ship electronics, reducing their offensive and defensive capabilities.',
    category: 'electronicWarfare',
    subCategory: 'offensive',
    displayGroup: 'Fleet Disruption Chance',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 10,
    sources: [
      { type: 'technology', label: 'EMP Tech', weight: 0.5 },
      { type: 'commander', label: 'Tactical Skill', weight: 0.3 },
      { type: 'item', label: 'EMP Generators', weight: 0.2 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.15 },
    tags: ['ewar', 'offensive', 'emp'],
  },
  fearBroadcastChance: {
    id: 'fearBroadcastChance',
    name: 'Fear Broadcast Chance',
    description: 'Chance to broadcast fear signals that reduce enemy morale and combat efficiency. Can cause enemy units to panic and flee.',
    category: 'electronicWarfare',
    subCategory: 'offensive',
    displayGroup: 'Fleet Disruption Chance',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 10,
    sources: [
      { type: 'technology', label: 'Psychic Tech', weight: 0.4 },
      { type: 'commander', label: 'Military Command', weight: 0.3 },
      { type: 'species', label: 'Terrifying Presence', weight: 0.3 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.12 },
    tags: ['ewar', 'offensive', 'fear'],
  },
  tractorBeamChance: {
    id: 'tractorBeamChance',
    name: 'Tractor Beam Chance',
    description: 'Chance to successfully grapple an enemy ship with a tractor beam. Tethered ships cannot retreat and suffer accuracy penalties.',
    category: 'electronicWarfare',
    subCategory: 'offensive',
    displayGroup: 'Fleet Disruption Chance',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 10,
    sources: [
      { type: 'technology', label: 'Gravity Tech', weight: 0.5 },
      { type: 'commander', label: 'Engineering', weight: 0.3 },
      { type: 'building', label: 'Gravity Projector', weight: 0.2 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.12 },
    tags: ['ewar', 'offensive', 'tractor'],
  },
  ionLockChance: {
    id: 'ionLockChance',
    name: 'Ion Lock Chance',
    description: 'Chance to ion-lock enemy ship engines, temporarily immobilizing them. Ion-locked ships cannot maneuver, greatly reducing evasion.',
    category: 'electronicWarfare',
    subCategory: 'offensive',
    displayGroup: 'Fleet Disruption Chance',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 10,
    sources: [
      { type: 'technology', label: 'Ion Tech', weight: 0.5 },
      { type: 'commander', label: 'Engineering', weight: 0.3 },
      { type: 'item', label: 'Ion Cannons', weight: 0.2 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.12 },
    tags: ['ewar', 'offensive', 'ion'],
  },
  sleepVirusChance: {
    id: 'sleepVirusChance',
    name: 'Sleep Virus Chance',
    description: 'Chance to deploy a sleep virus that puts enemy crew into stasis. Affected ships become inactive and cannot attack or defend for a duration.',
    category: 'electronicWarfare',
    subCategory: 'offensive',
    displayGroup: 'Fleet Disruption Chance',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 10,
    sources: [
      { type: 'technology', label: 'Bio-Weapon Tech', weight: 0.5 },
      { type: 'commander', label: 'Scientific Research', weight: 0.3 },
      { type: 'species', label: 'Toxin Resistance Bypass', weight: 0.2 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.1 },
    tags: ['ewar', 'offensive', 'virus'],
  },
  collisionAttackChance: {
    id: 'collisionAttackChance',
    name: 'Collision Attack Chance',
    description: 'Chance to execute a ramming/collision attack. These attacks sacrifice the ramming ship but deal massive damage ignoring most defenses.',
    category: 'electronicWarfare',
    subCategory: 'offensive',
    displayGroup: 'Fleet Disruption Chance',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 5,
    sources: [
      { type: 'technology', label: 'Ramming Techniques', weight: 0.4 },
      { type: 'commander', label: 'Military Command', weight: 0.3 },
      { type: 'species', label: 'Reckless Aggression', weight: 0.3 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.15 },
    tags: ['ewar', 'offensive', 'collision'],
  },
  signalJamChance: {
    id: 'signalJamChance',
    name: 'Signal Jam Chance',
    description: 'Chance to jam enemy communications and sensor signals. Jamming reduces enemy fleet coordination, accuracy, and can prevent reinforcements.',
    category: 'electronicWarfare',
    subCategory: 'offensive',
    displayGroup: 'Fleet Disruption Chance',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 10,
    sources: [
      { type: 'technology', label: 'Jammer Tech', weight: 0.5 },
      { type: 'commander', label: 'Sensor Operations', weight: 0.3 },
      { type: 'building', label: 'Jammer Array', weight: 0.2 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.12 },
    tags: ['ewar', 'offensive', 'jamming'],
  },
  systemCorruptionChance: {
    id: 'systemCorruptionChance',
    name: 'System Corruption Chance',
    description: 'Chance to corrupt enemy ship systems with malicious code. Corrupted systems malfunction randomly, reducing combat effectiveness across the board.',
    category: 'electronicWarfare',
    subCategory: 'offensive',
    displayGroup: 'Fleet Disruption Chance',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 10,
    sources: [
      { type: 'technology', label: 'Cyber Warfare', weight: 0.5 },
      { type: 'commander', label: 'Scientific Research', weight: 0.3 },
      { type: 'building', label: 'Data Nexus', weight: 0.2 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.12 },
    tags: ['ewar', 'offensive', 'corruption'],
  },

  // ===== PVP =====
  pvpFleetCriticalChance: {
    id: 'pvpFleetCriticalChance',
    name: 'Fleet Critical Chance (PvP)',
    description: 'Critical hit chance specifically in PvP combat. May differ from PvE crit chance due to player target countermeasures.',
    category: 'pvp',
    subCategory: 'critical',
    displayGroup: 'PvP Warfare',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 100,
    sources: [
      { type: 'technology', label: 'PvP Targeting Algorithms', weight: 0.4 },
      { type: 'commander', label: 'Tactical Skill', weight: 0.3 },
      { type: 'item', label: 'Player Hunter Module', weight: 0.3 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.1 },
    tags: ['pvp', 'critical', 'offense'],
  },
  pvpMissileCriticalChance: {
    id: 'pvpMissileCriticalChance',
    name: 'Missile Critical Chance (PvP)',
    description: 'Missile critical hit chance in PvP. Player point defense systems are more sophisticated than NPC ones.',
    category: 'pvp',
    subCategory: 'critical',
    displayGroup: 'PvP Warfare',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 80,
    sources: [
      { type: 'technology', label: 'PvP Warhead Tech', weight: 0.5 },
      { type: 'commander', label: 'Tactical Skill', weight: 0.3 },
      { type: 'item', label: 'Penetrator Module', weight: 0.2 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.08 },
    tags: ['pvp', 'critical', 'missile'],
  },
  pvpEnergyCriticalChance: {
    id: 'pvpEnergyCriticalChance',
    name: 'Energy Critical Chance (PvP)',
    description: 'Energy weapon critical hit chance in PvP. Player shield modulation makes energy crits harder to land.',
    category: 'pvp',
    subCategory: 'critical',
    displayGroup: 'PvP Warfare',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 80,
    sources: [
      { type: 'technology', label: 'PvP Focus Tech', weight: 0.5 },
      { type: 'commander', label: 'Engineering', weight: 0.3 },
      { type: 'item', label: 'Frequency Crystals', weight: 0.2 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.08 },
    tags: ['pvp', 'critical', 'energy'],
  },
  pvpFleetAccuracy: {
    id: 'pvpFleetAccuracy',
    name: 'Fleet Accuracy (PvP)',
    description: 'Fleet accuracy specifically against player targets. Player ships have better evasion than NPCs, requiring higher accuracy.',
    category: 'pvp',
    subCategory: 'accuracy',
    displayGroup: 'PvP Warfare',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 99999,
    defaultBase: 100,
    sources: [
      { type: 'technology', label: 'PvP Targeting Systems', weight: 0.4 },
      { type: 'commander', label: 'Sensor Operations', weight: 0.3 },
      { type: 'item', label: 'PvP Tracking Module', weight: 0.3 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.12 },
    tags: ['pvp', 'accuracy', 'offense'],
  },
  pvpFleetEvasion: {
    id: 'pvpFleetEvasion',
    name: 'Fleet Evasion (PvP)',
    description: 'Fleet evasion specifically against player attacks. PvP evasion is higher due to unpredictable piloting patterns.',
    category: 'pvp',
    subCategory: 'evasion',
    displayGroup: 'PvP Warfare',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 99999,
    defaultBase: 100,
    sources: [
      { type: 'technology', label: 'PvP Maneuvering', weight: 0.4 },
      { type: 'commander', label: 'Tactical Skill', weight: 0.3 },
      { type: 'item', label: 'Afterburner Module', weight: 0.3 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.12 },
    tags: ['pvp', 'evasion', 'defense'],
  },
  pvpHeavyStrikeChance: {
    id: 'pvpHeavyStrikeChance',
    name: 'Heavy Strike Chance (PvP)',
    description: 'Heavy strike chance in PvP combat. Critical for breaking through player tank setups.',
    category: 'pvp',
    subCategory: 'critical',
    displayGroup: 'PvP Warfare',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 50,
    sources: [
      { type: 'technology', label: 'Siege Tech (PvP)', weight: 0.4 },
      { type: 'commander', label: 'Military Command', weight: 0.3 },
      { type: 'item', label: 'Armor Shredder', weight: 0.3 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.1 },
    tags: ['pvp', 'heavy', 'offense'],
  },
  pvpHeavyStrikeEvasion: {
    id: 'pvpHeavyStrikeEvasion',
    name: 'Heavy Strike Evasion (PvP)',
    description: 'Evasion against heavy strikes in PvP. Player skill at dodging telegraphed heavy attacks matters more here.',
    category: 'pvp',
    subCategory: 'evasion',
    displayGroup: 'PvP Warfare',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 50,
    sources: [
      { type: 'technology', label: 'Reactive Maneuvering', weight: 0.4 },
      { type: 'commander', label: 'Tactical Skill', weight: 0.3 },
      { type: 'species', label: 'Reflex Bonus', weight: 0.3 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.1 },
    tags: ['pvp', 'evasion', 'defense'],
  },
  pvpDamageBonus: {
    id: 'pvpDamageBonus',
    name: 'PvP Damage Bonus',
    description: 'Percentage damage bonus specifically against player-controlled targets. Encourages and rewards player-versus-player engagement.',
    category: 'pvp',
    subCategory: 'damage',
    displayGroup: 'PvP Warfare',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 200,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'PvP Warfare Tech', weight: 0.4 },
      { type: 'commander', label: 'Military Command', weight: 0.3 },
      { type: 'species', label: 'War-like Species', weight: 0.3 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.3, denominator: 100 },
    tags: ['pvp', 'damage', 'bonus'],
  },

  // ===== PVE =====
  alienDamageReduction: {
    id: 'alienDamageReduction',
    name: 'Alien Damage Reduction',
    description: 'Flat damage reduction against alien and NPC faction attacks. Represents specialized countermeasures against non-humanoid opponents.',
    category: 'pve',
    subCategory: 'defense',
    displayGroup: 'PvE (NPC & Alien Empires)',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 999,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Xeno Studies', weight: 0.5 },
      { type: 'commander', label: 'Scientific Research', weight: 0.3 },
      { type: 'species', label: 'Ancient Knowledge', weight: 0.2 },
    ],
    scaling: { type: 'linear', factorPerLevel: 1 },
    tags: ['pve', 'defense', 'alien'],
  },
  pveFleetAccuracy: {
    id: 'pveFleetAccuracy',
    name: 'Fleet Accuracy (PvE)',
    description: 'Fleet accuracy against NPC targets. Generally higher than PvP accuracy since NPCs have predictable movement patterns.',
    category: 'pve',
    subCategory: 'accuracy',
    displayGroup: 'PvE (NPC & Alien Empires)',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 99999,
    defaultBase: 100,
    sources: [
      { type: 'technology', label: 'Xeno Targeting', weight: 0.4 },
      { type: 'commander', label: 'Sensor Operations', weight: 0.3 },
      { type: 'item', label: 'NPC Tracker', weight: 0.3 },
    ],
    scaling: { type: 'exponential', factorPerLevel: 1.1 },
    tags: ['pve', 'accuracy', 'offense'],
  },
  pveFleetCriticalChance: {
    id: 'pveFleetCriticalChance',
    name: 'Fleet Critical Chance (PvE)',
    description: 'Critical hit chance against NPC targets. NPC weak points are easier to exploit than player-controlled ships.',
    category: 'pve',
    subCategory: 'critical',
    displayGroup: 'PvE (NPC & Alien Empires)',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 95,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Xeno Anatomy', weight: 0.4 },
      { type: 'commander', label: 'Tactical Skill', weight: 0.3 },
      { type: 'species', label: 'Hunter Instinct', weight: 0.3 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.5, denominator: 100 },
    tags: ['pve', 'critical', 'offense'],
  },
  pveFleetHeavyStrikeChance: {
    id: 'pveFleetHeavyStrikeChance',
    name: 'Fleet Heavy Strike Chance (PvE)',
    description: 'Heavy strike chance against NPC targets. Alien and NPC ships often have predictable vulnerability windows.',
    category: 'pve',
    subCategory: 'critical',
    displayGroup: 'PvE (NPC & Alien Empires)',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 95,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Xeno Weakpoint Analysis', weight: 0.4 },
      { type: 'commander', label: 'Scientific Research', weight: 0.3 },
      { type: 'item', label: 'Scanner Module', weight: 0.3 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.6, denominator: 100 },
    tags: ['pve', 'heavy', 'offense'],
  },
  pveFleetEvasion: {
    id: 'pveFleetEvasion',
    name: 'Fleet Evasion (PvE)',
    description: 'Fleet evasion against NPC attacks. NPC accuracy is typically lower than player accuracy, making evasion more effective.',
    category: 'pve',
    subCategory: 'evasion',
    displayGroup: 'PvE (NPC & Alien Empires)',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 95,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'NPC Countermeasures', weight: 0.4 },
      { type: 'commander', label: 'Tactical Skill', weight: 0.3 },
      { type: 'formation', label: 'Anti-Alien Formation', weight: 0.3 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.5, denominator: 80 },
    tags: ['pve', 'evasion', 'defense'],
  },
  pveHeavyStrikeEvasion: {
    id: 'pveHeavyStrikeEvasion',
    name: 'Heavy Strike Evasion (PvE)',
    description: 'Evasion against NPC heavy strikes. Alien heavy attacks are often telegraphed with long wind-up animations, making them easier to dodge.',
    category: 'pve',
    subCategory: 'evasion',
    displayGroup: 'PvE (NPC & Alien Empires)',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 95,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'NPC Pattern Recognition', weight: 0.4 },
      { type: 'commander', label: 'Tactical Skill', weight: 0.3 },
      { type: 'species', label: 'Natural Reflexes', weight: 0.3 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.3, denominator: 80 },
    tags: ['pve', 'evasion', 'defense'],
  },

  // ===== TACTICAL COMBAT =====
  flankingAccuracy: {
    id: 'flankingAccuracy',
    name: 'Flanking Accuracy',
    description: 'Accuracy bonus when attacking from flanking positions. Flanking attacks bypass front-facing shields and armor.',
    category: 'tactical',
    subCategory: 'flanking',
    displayGroup: 'Tactical Combat',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 10,
    sources: [
      { type: 'commander', label: 'Tactical Skill', weight: 0.5 },
      { type: 'technology', label: 'Flanking Maneuvers', weight: 0.3 },
      { type: 'formation', label: 'Flanking Formation', weight: 0.2 },
    ],
    scaling: { type: 'linear', factorPerLevel: 3 },
    tags: ['tactical', 'flanking', 'accuracy'],
  },
  flankingEvasion: {
    id: 'flankingEvasion',
    name: 'Flanking Evasion',
    description: 'Evasion bonus against enemy flanking maneuvers. Prevents enemies from gaining advantageous flanking positions against your fleet.',
    category: 'tactical',
    subCategory: 'flanking',
    displayGroup: 'Tactical Combat',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 10,
    sources: [
      { type: 'commander', label: 'Tactical Skill', weight: 0.5 },
      { type: 'technology', label: 'Anti-Flank Sensors', weight: 0.3 },
      { type: 'formation', label: 'Fortress Formation', weight: 0.2 },
    ],
    scaling: { type: 'linear', factorPerLevel: 3 },
    tags: ['tactical', 'flanking', 'evasion'],
  },
  rearAssaultHeavyStrike: {
    id: 'rearAssaultHeavyStrike',
    name: 'Rear Assault Heavy Strike',
    description: 'Effectiveness of heavy strikes performed from rear positions. Rear attacks bypass most defenses and deal critical damage.',
    category: 'tactical',
    subCategory: 'flanking',
    displayGroup: 'Tactical Combat',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 9999,
    defaultBase: 10,
    sources: [
      { type: 'commander', label: 'Military Command', weight: 0.5 },
      { type: 'technology', label: 'Ambush Tactics', weight: 0.3 },
      { type: 'species', label: 'Stealth Affinity', weight: 0.2 },
    ],
    scaling: { type: 'linear', factorPerLevel: 4 },
    tags: ['tactical', 'heavy', 'rear'],
  },

  // ===== EMPIRE BONUSES =====
  empireSpeciesCombatBonus: {
    id: 'empireSpeciesCombatBonus',
    name: 'Species Combat Bonus',
    description: 'Overall combat bonus derived from empire species choice. This is the species-wide combat bonus applied to all fleets and commanders.',
    category: 'bonuses',
    subCategory: 'species',
    displayGroup: 'Empire Bonuses',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 200,
    defaultBase: 0,
    sources: [
      { type: 'species', label: 'Species Trait', weight: 0.8 },
      { type: 'technology', label: 'Genetic Enhancement', weight: 0.2 },
    ],
    scaling: { type: 'linear', factorPerLevel: 0 },
    tags: ['species', 'combat', 'bonus'],
  },
  humanoidEmpireDamageBonus: {
    id: 'humanoidEmpireDamageBonus',
    name: 'Humanoid Empire Damage Bonus',
    description: 'Bonus damage against humanoid empire targets. Represents specialized tactics and technology for combating other humanoid civilizations.',
    category: 'bonuses',
    subCategory: 'combat',
    displayGroup: 'Empire Bonuses',
    isPercentage: false,
    isMillable: true,
    minValue: 0,
    maxValue: 500,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Anti-Personnel Tech', weight: 0.5 },
      { type: 'species', label: 'Rivalry Trait', weight: 0.3 },
      { type: 'commander', label: 'Military Command', weight: 0.2 },
    ],
    scaling: { type: 'linear', factorPerLevel: 5 },
    tags: ['bonus', 'damage', 'humanoid'],
  },
  weaponTechnologyBonus: {
    id: 'weaponTechnologyBonus',
    name: 'Weapon Technology Bonus',
    description: 'Percentage bonus to all weapon damage from cumulative weapon technology research. Stacks additively with other percentage bonuses.',
    category: 'bonuses',
    subCategory: 'technology',
    displayGroup: 'Empire Bonuses',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 500,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'All Weapon Techs', weight: 0.7 },
      { type: 'research', label: 'Applied Weapon Research', weight: 0.3 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 2, denominator: 250 },
    tags: ['bonus', 'weapon', 'technology'],
  },
  fleetDamageBonus: {
    id: 'fleetDamageBonus',
    name: 'Fleet Damage Bonus',
    description: 'Global fleet damage percentage bonus. Applied to all fleet attacks as a final damage multiplier. Represents overall fleet doctrine improvements.',
    category: 'bonuses',
    subCategory: 'combat',
    displayGroup: 'Empire Bonuses',
    isPercentage: true,
    isMillable: true,
    minValue: 0,
    maxValue: 200,
    defaultBase: 0,
    sources: [
      { type: 'technology', label: 'Fleet Doctrine Tech', weight: 0.4 },
      { type: 'commander', label: 'Military Command', weight: 0.3 },
      { type: 'building', label: 'War Academy', weight: 0.3 },
    ],
    scaling: { type: 'diminishing', factorPerLevel: 0.5, denominator: 150 },
    tags: ['bonus', 'damage', 'fleet'],
  },
};

export function getStatsByCategory(category: EmpireStatCategory): StatMetadata[] {
  return Object.values(STAT_METADATA).filter(s => s.category === category);
}

export function getStatsBySubCategory(category: EmpireStatCategory, subCategory: string): StatMetadata[] {
  return Object.values(STAT_METADATA).filter(s => s.category === category && s.subCategory === subCategory);
}

export function getStatsByTag(tag: string): StatMetadata[] {
  return Object.values(STAT_METADATA).filter(s => s.tags.includes(tag));
}

export function getMetadata(statId: string): StatMetadata | undefined {
  return STAT_METADATA[statId];
}
