import { type EmpireCombatStats } from './empireStatsConfig';

export interface TierExample {
  tier: number;
  level: number;
  label: string;
  stats: EmpireCombatStats;
}

function pct(v: number) { return v; }
function flat(v: number) { return v; }

export const TIER_EXAMPLES: TierExample[] = [
  {
    tier: 1,
    level: 1,
    label: 'Starting Empire',
    stats: {
      fleet: {
        firepower: {
          attackPower: 10,
          weaponSystemsBonus: 0,
          attackSpeed: 1.0,
          combatEfficiency: 100,
          engagementRange: 1.0,
          sensorRangeBonus: 0,
          speciesCombatBonus: 0,
        },
        accuracy: {
          fleetAccuracy: 100,
          missileAccuracy: 80,
          energyWeaponAccuracy: 80,
          commanderTargetingBonus: 0,
        },
        critical: {
          fleetCriticalChance: 0,
          missileCriticalChance: 0,
          energyCriticalChance: 0,
          fleetHeavyStrike: 0,
          missileHeavyStrike: 0,
          energyHeavyStrike: 0,
          criticalDamageBonus: 50,
          heavyStrikeDamage: 25,
        },
        defense: {
          fleetArmor: 50,
          shieldRating: 50,
          energyShield: 20,
          hullDamageReduction: 0,
          criticalDamageResistance: 0,
          heavyStrikeResistance: 0,
          fleetDamageResistance: 0,
        },
        evasion: {
          fleetEvasion: 0,
          missileEvasion: 0,
          energyWeaponEvasion: 0,
          heavyStrikeEvasion: 0,
          rearAssaultAvoidance: 0,
        },
      },
      empire: {
        commander: {
          militaryCommand: 5,
          engineering: 5,
          scientificResearch: 5,
          sensorOperations: 5,
          empireLogistics: 5,
        },
        resources: {
          maxPopulation: 500,
          populationGrowth: 10,
          maxEnergy: 500,
          energyRegeneration: 20,
          energyEfficiency: 0,
        },
        mobility: {
          warpSpeedBonus: 0,
          maxWarpCapacity: 5,
          warpRechargeRate: 0.5,
        },
      },
      technology: {
        researchEfficiency: 0,
        technologyCooldownReduction: 0,
        infrastructureEfficiency: 0,
        buffDuration: 0,
        enemyDebuffDuration: 0,
        repairEfficiency: 0,
        colonyHealingBonus: 0,
      },
      resistance: {
        empResistance: 10,
        jammingResistance: 10,
        sensorBlindResistance: 10,
        hackResistance: 10,
        communicationsResistance: 10,
        panicResistance: 10,
        tractorBeamResistance: 50,
        collisionResistance: 100,
      },
      electronicWarfare: {
        empChance: 10,
        fearBroadcastChance: 10,
        tractorBeamChance: 10,
        ionLockChance: 10,
        sleepVirusChance: 10,
        collisionAttackChance: 5,
        signalJamChance: 10,
        systemCorruptionChance: 10,
      },
      pvp: {
        fleetCriticalChance: 100,
        missileCriticalChance: 80,
        energyCriticalChance: 80,
        fleetAccuracy: 100,
        fleetEvasion: 100,
        heavyStrikeChance: 50,
        heavyStrikeEvasion: 50,
        pvpDamageBonus: 0,
      },
      pve: {
        alienDamageReduction: 0,
        fleetAccuracy: 100,
        fleetCriticalChance: 0,
        fleetHeavyStrikeChance: 0,
        fleetEvasion: 0,
        heavyStrikeEvasion: 0,
      },
      tactical: {
        flankingAccuracy: 10,
        flankingEvasion: 10,
        rearAssaultHeavyStrike: 10,
      },
      bonuses: {
        speciesCombatBonus: 0,
        humanoidEmpireDamageBonus: 0,
        weaponTechnologyBonus: 0,
        fleetDamageBonus: 0,
      },
    },
  },
  {
    tier: 2,
    level: 25,
    label: 'Developing Empire',
    stats: {
      fleet: {
        firepower: {
          attackPower: 68,
          weaponSystemsBonus: 5,
          attackSpeed: 0.85,
          combatEfficiency: 105,
          engagementRange: 1.5,
          sensorRangeBonus: 2,
          speciesCombatBonus: 5,
        },
        accuracy: {
          fleetAccuracy: 450,
          missileAccuracy: 350,
          energyWeaponAccuracy: 350,
          commanderTargetingBonus: 25,
        },
        critical: {
          fleetCriticalChance: 5,
          missileCriticalChance: 3,
          energyCriticalChance: 3,
          fleetHeavyStrike: 3,
          missileHeavyStrike: 2,
          energyHeavyStrike: 2,
          criticalDamageBonus: 55,
          heavyStrikeDamage: 28,
        },
        defense: {
          fleetArmor: 250,
          shieldRating: 280,
          energyShield: 120,
          hullDamageReduction: 5,
          criticalDamageResistance: 2,
          heavyStrikeResistance: 3,
          fleetDamageResistance: 5,
        },
        evasion: {
          fleetEvasion: 8,
          missileEvasion: 5,
          energyWeaponEvasion: 5,
          heavyStrikeEvasion: 2,
          rearAssaultAvoidance: 3,
        },
      },
      empire: {
        commander: {
          militaryCommand: 20,
          engineering: 18,
          scientificResearch: 15,
          sensorOperations: 16,
          empireLogistics: 14,
        },
        resources: {
          maxPopulation: 2500,
          populationGrowth: 45,
          maxEnergy: 1800,
          energyRegeneration: 80,
          energyEfficiency: 2,
        },
        mobility: {
          warpSpeedBonus: 5,
          maxWarpCapacity: 8,
          warpRechargeRate: 0.7,
        },
      },
      technology: {
        researchEfficiency: 5,
        technologyCooldownReduction: 3,
        infrastructureEfficiency: 4,
        buffDuration: 10,
        enemyDebuffDuration: -5,
        repairEfficiency: 3,
        colonyHealingBonus: 8,
      },
      resistance: {
        empResistance: 50,
        jammingResistance: 50,
        sensorBlindResistance: 50,
        hackResistance: 50,
        communicationsResistance: 50,
        panicResistance: 50,
        tractorBeamResistance: 100,
        collisionResistance: 150,
      },
      electronicWarfare: {
        empChance: 60,
        fearBroadcastChance: 45,
        tractorBeamChance: 50,
        ionLockChance: 50,
        sleepVirusChance: 45,
        collisionAttackChance: 30,
        signalJamChance: 50,
        systemCorruptionChance: 45,
      },
      pvp: {
        fleetCriticalChance: 250,
        missileCriticalChance: 200,
        energyCriticalChance: 200,
        fleetAccuracy: 500,
        fleetEvasion: 450,
        heavyStrikeChance: 120,
        heavyStrikeEvasion: 100,
        pvpDamageBonus: 2,
      },
      pve: {
        alienDamageReduction: 5,
        fleetAccuracy: 450,
        fleetCriticalChance: 5,
        fleetHeavyStrikeChance: 3,
        fleetEvasion: 8,
        heavyStrikeEvasion: 2,
      },
      tactical: {
        flankingAccuracy: 30,
        flankingEvasion: 35,
        rearAssaultHeavyStrike: 25,
      },
      bonuses: {
        speciesCombatBonus: 5,
        humanoidEmpireDamageBonus: 3,
        weaponTechnologyBonus: 2,
        fleetDamageBonus: 1,
      },
    },
  },
  {
    tier: 3,
    level: 50,
    label: 'Established Empire',
    stats: {
      fleet: {
        firepower: {
          attackPower: 280,
          weaponSystemsBonus: 12,
          attackSpeed: 0.72,
          combatEfficiency: 112,
          engagementRange: 2.5,
          sensorRangeBonus: 5,
          speciesCombatBonus: 18,
        },
        accuracy: {
          fleetAccuracy: 1200,
          missileAccuracy: 950,
          energyWeaponAccuracy: 950,
          commanderTargetingBonus: 80,
        },
        critical: {
          fleetCriticalChance: 15,
          missileCriticalChance: 10,
          energyCriticalChance: 10,
          fleetHeavyStrike: 12,
          missileHeavyStrike: 8,
          energyHeavyStrike: 8,
          criticalDamageBonus: 62,
          heavyStrikeDamage: 35,
        },
        defense: {
          fleetArmor: 850,
          shieldRating: 920,
          energyShield: 450,
          hullDamageReduction: 12,
          criticalDamageResistance: 5,
          heavyStrikeResistance: 7,
          fleetDamageResistance: 12,
        },
        evasion: {
          fleetEvasion: 22,
          missileEvasion: 15,
          energyWeaponEvasion: 16,
          heavyStrikeEvasion: 7,
          rearAssaultAvoidance: 9,
        },
      },
      empire: {
        commander: {
          militaryCommand: 45,
          engineering: 42,
          scientificResearch: 35,
          sensorOperations: 38,
          empireLogistics: 30,
        },
        resources: {
          maxPopulation: 8500,
          populationGrowth: 120,
          maxEnergy: 4500,
          energyRegeneration: 180,
          energyEfficiency: 5,
        },
        mobility: {
          warpSpeedBonus: 12,
          maxWarpCapacity: 12,
          warpRechargeRate: 0.9,
        },
      },
      technology: {
        researchEfficiency: 12,
        technologyCooldownReduction: 8,
        infrastructureEfficiency: 10,
        buffDuration: 25,
        enemyDebuffDuration: -10,
        repairEfficiency: 8,
        colonyHealingBonus: 22,
      },
      resistance: {
        empResistance: 120,
        jammingResistance: 120,
        sensorBlindResistance: 120,
        hackResistance: 120,
        communicationsResistance: 120,
        panicResistance: 120,
        tractorBeamResistance: 180,
        collisionResistance: 240,
      },
      electronicWarfare: {
        empChance: 180,
        fearBroadcastChance: 140,
        tractorBeamChance: 150,
        ionLockChance: 150,
        sleepVirusChance: 140,
        collisionAttackChance: 100,
        signalJamChance: 150,
        systemCorruptionChance: 140,
      },
      pvp: {
        fleetCriticalChance: 550,
        missileCriticalChance: 420,
        energyCriticalChance: 420,
        fleetAccuracy: 1100,
        fleetEvasion: 950,
        heavyStrikeChance: 320,
        heavyStrikeEvasion: 200,
        pvpDamageBonus: 5,
      },
      pve: {
        alienDamageReduction: 12,
        fleetAccuracy: 1200,
        fleetCriticalChance: 15,
        fleetHeavyStrikeChance: 12,
        fleetEvasion: 22,
        heavyStrikeEvasion: 7,
      },
      tactical: {
        flankingAccuracy: 65,
        flankingEvasion: 75,
        rearAssaultHeavyStrike: 55,
      },
      bonuses: {
        speciesCombatBonus: 18,
        humanoidEmpireDamageBonus: 8,
        weaponTechnologyBonus: 5,
        fleetDamageBonus: 3,
      },
    },
  },
  {
    tier: 5,
    level: 100,
    label: 'Regional Power',
    stats: {
      fleet: {
        firepower: {
          attackPower: 1200,
          weaponSystemsBonus: 25,
          attackSpeed: 0.55,
          combatEfficiency: 125,
          engagementRange: 4.0,
          sensorRangeBonus: 10,
          speciesCombatBonus: 45,
        },
        accuracy: {
          fleetAccuracy: 3500,
          missileAccuracy: 2800,
          energyWeaponAccuracy: 2800,
          commanderTargetingBonus: 220,
        },
        critical: {
          fleetCriticalChance: 35,
          missileCriticalChance: 28,
          energyCriticalChance: 28,
          fleetHeavyStrike: 30,
          missileHeavyStrike: 22,
          energyHeavyStrike: 22,
          criticalDamageBonus: 80,
          heavyStrikeDamage: 50,
        },
        defense: {
          fleetArmor: 2800,
          shieldRating: 3100,
          energyShield: 1800,
          hullDamageReduction: 28,
          criticalDamageResistance: 12,
          heavyStrikeResistance: 16,
          fleetDamageResistance: 25,
        },
        evasion: {
          fleetEvasion: 48,
          missileEvasion: 35,
          energyWeaponEvasion: 36,
          heavyStrikeEvasion: 16,
          rearAssaultAvoidance: 20,
        },
      },
      empire: {
        commander: {
          militaryCommand: 85,
          engineering: 80,
          scientificResearch: 70,
          sensorOperations: 75,
          empireLogistics: 65,
        },
        resources: {
          maxPopulation: 28000,
          populationGrowth: 250,
          maxEnergy: 14000,
          energyRegeneration: 380,
          energyEfficiency: 8,
        },
        mobility: {
          warpSpeedBonus: 22,
          maxWarpCapacity: 18,
          warpRechargeRate: 1.3,
        },
      },
      technology: {
        researchEfficiency: 25,
        technologyCooldownReduction: 18,
        infrastructureEfficiency: 20,
        buffDuration: 50,
        enemyDebuffDuration: -20,
        repairEfficiency: 15,
        colonyHealingBonus: 42,
      },
      resistance: {
        empResistance: 260,
        jammingResistance: 260,
        sensorBlindResistance: 260,
        hackResistance: 260,
        communicationsResistance: 260,
        panicResistance: 260,
        tractorBeamResistance: 320,
        collisionResistance: 390,
      },
      electronicWarfare: {
        empChance: 450,
        fearBroadcastChance: 350,
        tractorBeamChance: 380,
        ionLockChance: 380,
        sleepVirusChance: 350,
        collisionAttackChance: 280,
        signalJamChance: 380,
        systemCorruptionChance: 350,
      },
      pvp: {
        fleetCriticalChance: 1100,
        missileCriticalChance: 850,
        energyCriticalChance: 850,
        fleetAccuracy: 2400,
        fleetEvasion: 2000,
        heavyStrikeChance: 700,
        heavyStrikeEvasion: 350,
        pvpDamageBonus: 8,
      },
      pve: {
        alienDamageReduction: 28,
        fleetAccuracy: 3500,
        fleetCriticalChance: 35,
        fleetHeavyStrikeChance: 30,
        fleetEvasion: 48,
        heavyStrikeEvasion: 16,
      },
      tactical: {
        flankingAccuracy: 110,
        flankingEvasion: 130,
        rearAssaultHeavyStrike: 100,
      },
      bonuses: {
        speciesCombatBonus: 45,
        humanoidEmpireDamageBonus: 15,
        weaponTechnologyBonus: 10,
        fleetDamageBonus: 5,
      },
    },
  },
  {
    tier: 8,
    level: 200,
    label: 'Galactic Contender',
    stats: {
      fleet: {
        firepower: {
          attackPower: 5800,
          weaponSystemsBonus: 50,
          attackSpeed: 0.36,
          combatEfficiency: 145,
          engagementRange: 6.5,
          sensorRangeBonus: 18,
          speciesCombatBonus: 90,
        },
        accuracy: {
          fleetAccuracy: 12000,
          missileAccuracy: 9500,
          energyWeaponAccuracy: 9500,
          commanderTargetingBonus: 600,
        },
        critical: {
          fleetCriticalChance: 55,
          missileCriticalChance: 48,
          energyCriticalChance: 48,
          fleetHeavyStrike: 52,
          missileHeavyStrike: 42,
          energyHeavyStrike: 42,
          criticalDamageBonus: 110,
          heavyStrikeDamage: 72,
        },
        defense: {
          fleetArmor: 9500,
          shieldRating: 10500,
          energyShield: 6500,
          hullDamageReduction: 55,
          criticalDamageResistance: 22,
          heavyStrikeResistance: 30,
          fleetDamageResistance: 42,
        },
        evasion: {
          fleetEvasion: 68,
          missileEvasion: 52,
          energyWeaponEvasion: 54,
          heavyStrikeEvasion: 25,
          rearAssaultAvoidance: 30,
        },
      },
      empire: {
        commander: {
          militaryCommand: 160,
          engineering: 150,
          scientificResearch: 130,
          sensorOperations: 140,
          empireLogistics: 120,
        },
        resources: {
          maxPopulation: 85000,
          populationGrowth: 550,
          maxEnergy: 42000,
          energyRegeneration: 750,
          energyEfficiency: 12,
        },
        mobility: {
          warpSpeedBonus: 38,
          maxWarpCapacity: 28,
          warpRechargeRate: 2.0,
        },
      },
      technology: {
        researchEfficiency: 45,
        technologyCooldownReduction: 32,
        infrastructureEfficiency: 38,
        buffDuration: 90,
        enemyDebuffDuration: -35,
        repairEfficiency: 28,
        colonyHealingBonus: 72,
      },
      resistance: {
        empResistance: 500,
        jammingResistance: 500,
        sensorBlindResistance: 500,
        hackResistance: 500,
        communicationsResistance: 500,
        panicResistance: 500,
        tractorBeamResistance: 560,
        collisionResistance: 630,
      },
      electronicWarfare: {
        empChance: 1100,
        fearBroadcastChance: 850,
        tractorBeamChance: 920,
        ionLockChance: 920,
        sleepVirusChance: 850,
        collisionAttackChance: 750,
        signalJamChance: 920,
        systemCorruptionChance: 850,
      },
      pvp: {
        fleetCriticalChance: 2500,
        missileCriticalChance: 1900,
        energyCriticalChance: 1900,
        fleetAccuracy: 5200,
        fleetEvasion: 4800,
        heavyStrikeChance: 1600,
        heavyStrikeEvasion: 650,
        pvpDamageBonus: 12,
      },
      pve: {
        alienDamageReduction: 55,
        fleetAccuracy: 12000,
        fleetCriticalChance: 55,
        fleetHeavyStrikeChance: 52,
        fleetEvasion: 68,
        heavyStrikeEvasion: 25,
      },
      tactical: {
        flankingAccuracy: 200,
        flankingEvasion: 240,
        rearAssaultHeavyStrike: 180,
      },
      bonuses: {
        speciesCombatBonus: 90,
        humanoidEmpireDamageBonus: 30,
        weaponTechnologyBonus: 20,
        fleetDamageBonus: 8,
      },
    },
  },
  {
    tier: 10,
    level: 350,
    label: 'Ascendant Empire',
    stats: {
      fleet: {
        firepower: {
          attackPower: 18000,
          weaponSystemsBonus: 85,
          attackSpeed: 0.22,
          combatEfficiency: 170,
          engagementRange: 10.0,
          sensorRangeBonus: 30,
          speciesCombatBonus: 150,
        },
        accuracy: {
          fleetAccuracy: 35000,
          missileAccuracy: 28000,
          energyWeaponAccuracy: 28000,
          commanderTargetingBonus: 1500,
        },
        critical: {
          fleetCriticalChance: 72,
          missileCriticalChance: 65,
          energyCriticalChance: 65,
          fleetHeavyStrike: 70,
          missileHeavyStrike: 60,
          energyHeavyStrike: 60,
          criticalDamageBonus: 150,
          heavyStrikeDamage: 100,
        },
        defense: {
          fleetArmor: 28000,
          shieldRating: 31000,
          energyShield: 20000,
          hullDamageReduction: 90,
          criticalDamageResistance: 35,
          heavyStrikeResistance: 45,
          fleetDamageResistance: 60,
        },
        evasion: {
          fleetEvasion: 82,
          missileEvasion: 68,
          energyWeaponEvasion: 70,
          heavyStrikeEvasion: 35,
          rearAssaultAvoidance: 42,
        },
      },
      empire: {
        commander: {
          militaryCommand: 280,
          engineering: 260,
          scientificResearch: 230,
          sensorOperations: 250,
          empireLogistics: 210,
        },
        resources: {
          maxPopulation: 220000,
          populationGrowth: 1100,
          maxEnergy: 110000,
          energyRegeneration: 1600,
          energyEfficiency: 18,
        },
        mobility: {
          warpSpeedBonus: 58,
          maxWarpCapacity: 40,
          warpRechargeRate: 3.0,
        },
      },
      technology: {
        researchEfficiency: 70,
        technologyCooldownReduction: 50,
        infrastructureEfficiency: 60,
        buffDuration: 150,
        enemyDebuffDuration: -50,
        repairEfficiency: 45,
        colonyHealingBonus: 110,
      },
      resistance: {
        empResistance: 800,
        jammingResistance: 800,
        sensorBlindResistance: 800,
        hackResistance: 800,
        communicationsResistance: 800,
        panicResistance: 800,
        tractorBeamResistance: 860,
        collisionResistance: 930,
      },
      electronicWarfare: {
        empChance: 2200,
        fearBroadcastChance: 1700,
        tractorBeamChance: 1850,
        ionLockChance: 1850,
        sleepVirusChance: 1700,
        collisionAttackChance: 1500,
        signalJamChance: 1850,
        systemCorruptionChance: 1700,
      },
      pvp: {
        fleetCriticalChance: 5000,
        missileCriticalChance: 3800,
        energyCriticalChance: 3800,
        fleetAccuracy: 10500,
        fleetEvasion: 9500,
        heavyStrikeChance: 3200,
        heavyStrikeEvasion: 1000,
        pvpDamageBonus: 18,
      },
      pve: {
        alienDamageReduction: 90,
        fleetAccuracy: 35000,
        fleetCriticalChance: 72,
        fleetHeavyStrikeChance: 70,
        fleetEvasion: 82,
        heavyStrikeEvasion: 35,
      },
      tactical: {
        flankingAccuracy: 350,
        flankingEvasion: 420,
        rearAssaultHeavyStrike: 320,
      },
      bonuses: {
        speciesCombatBonus: 150,
        humanoidEmpireDamageBonus: 50,
        weaponTechnologyBonus: 35,
        fleetDamageBonus: 12,
      },
    },
  },
];

export function getTierExample(tier: number): TierExample | undefined {
  return TIER_EXAMPLES.find(t => t.tier === tier);
}

export function getClosestTierExample(level: number): TierExample {
  let closest = TIER_EXAMPLES[0];
  for (const ex of TIER_EXAMPLES) {
    if (Math.abs(ex.level - level) < Math.abs(closest.level - level)) {
      closest = ex;
    }
  }
  return closest;
}
